// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "jet_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic jet_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic jet_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> jet_hw::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<6> jet_hw::ap_ST_fsm_pp0_stage1 = "10";
const sc_lv<6> jet_hw::ap_ST_fsm_pp0_stage2 = "100";
const sc_lv<6> jet_hw::ap_ST_fsm_pp0_stage3 = "1000";
const sc_lv<6> jet_hw::ap_ST_fsm_pp0_stage4 = "10000";
const sc_lv<6> jet_hw::ap_ST_fsm_pp0_stage5 = "100000";
const sc_lv<32> jet_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool jet_hw::ap_const_boolean_1 = true;
const sc_lv<32> jet_hw::ap_const_lv32_5 = "101";
const bool jet_hw::ap_const_boolean_0 = false;
const sc_lv<32> jet_hw::ap_const_lv32_3 = "11";
const sc_lv<32> jet_hw::ap_const_lv32_4 = "100";
const sc_lv<32> jet_hw::ap_const_lv32_1 = "1";
const sc_lv<32> jet_hw::ap_const_lv32_2 = "10";
const sc_lv<1> jet_hw::ap_const_lv1_0 = "0";
const sc_lv<17> jet_hw::ap_const_lv17_0 = "00000000000000000";
const sc_lv<32> jet_hw::ap_const_lv32_10 = "10000";
const sc_lv<16> jet_hw::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> jet_hw::ap_const_lv32_C = "1100";
const sc_lv<32> jet_hw::ap_const_lv32_F = "1111";
const sc_lv<4> jet_hw::ap_const_lv4_0 = "0000";
const sc_lv<16> jet_hw::ap_const_lv16_1 = "1";
const sc_lv<32> jet_hw::ap_const_lv32_9 = "1001";
const sc_lv<9> jet_hw::ap_const_lv9_100 = "100000000";
const sc_lv<10> jet_hw::ap_const_lv10_200 = "1000000000";
const sc_lv<10> jet_hw::ap_const_lv10_0 = "0000000000";
const sc_lv<11> jet_hw::ap_const_lv11_600 = "11000000000";
const sc_lv<1> jet_hw::ap_const_lv1_1 = "1";
const sc_lv<11> jet_hw::ap_const_lv11_0 = "00000000000";

jet_hw::jet_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    inv_table3_U = new jet_hw_inv_table3("inv_table3_U");
    inv_table3_U->clk(ap_clk);
    inv_table3_U->reset(ap_rst);
    inv_table3_U->address0(inv_table3_address0);
    inv_table3_U->ce0(inv_table3_ce0);
    inv_table3_U->q0(inv_table3_q0);
    atan_table4_U = new jet_hw_atan_table4("atan_table4_U");
    atan_table4_U->clk(ap_clk);
    atan_table4_U->reset(ap_rst);
    atan_table4_U->address0(atan_table4_address0);
    atan_table4_U->ce0(atan_table4_ce0);
    atan_table4_U->q0(atan_table4_q0);
    grp_ProjX_fu_276 = new ProjX("grp_ProjX_fu_276");
    grp_ProjX_fu_276->ap_clk(ap_clk);
    grp_ProjX_fu_276->ap_rst(ap_rst);
    grp_ProjX_fu_276->ap_start(grp_ProjX_fu_276_ap_start);
    grp_ProjX_fu_276->ap_done(grp_ProjX_fu_276_ap_done);
    grp_ProjX_fu_276->ap_idle(grp_ProjX_fu_276_ap_idle);
    grp_ProjX_fu_276->ap_ready(grp_ProjX_fu_276_ap_ready);
    grp_ProjX_fu_276->ap_ce(ap_var_for_const0);
    grp_ProjX_fu_276->pt_V(grp_ProjX_fu_276_pt_V);
    grp_ProjX_fu_276->phi_V(grp_ProjX_fu_276_phi_V);
    grp_ProjX_fu_276->ap_return(grp_ProjX_fu_276_ap_return);
    grp_ProjX_fu_286 = new ProjX("grp_ProjX_fu_286");
    grp_ProjX_fu_286->ap_clk(ap_clk);
    grp_ProjX_fu_286->ap_rst(ap_rst);
    grp_ProjX_fu_286->ap_start(grp_ProjX_fu_286_ap_start);
    grp_ProjX_fu_286->ap_done(grp_ProjX_fu_286_ap_done);
    grp_ProjX_fu_286->ap_idle(grp_ProjX_fu_286_ap_idle);
    grp_ProjX_fu_286->ap_ready(grp_ProjX_fu_286_ap_ready);
    grp_ProjX_fu_286->ap_ce(ap_var_for_const0);
    grp_ProjX_fu_286->pt_V(grp_ProjX_fu_286_pt_V);
    grp_ProjX_fu_286->phi_V(grp_ProjX_fu_286_phi_V);
    grp_ProjX_fu_286->ap_return(grp_ProjX_fu_286_ap_return);
    grp_ProjY_fu_312 = new ProjY("grp_ProjY_fu_312");
    grp_ProjY_fu_312->ap_clk(ap_clk);
    grp_ProjY_fu_312->ap_rst(ap_rst);
    grp_ProjY_fu_312->ap_start(grp_ProjY_fu_312_ap_start);
    grp_ProjY_fu_312->ap_done(grp_ProjY_fu_312_ap_done);
    grp_ProjY_fu_312->ap_idle(grp_ProjY_fu_312_ap_idle);
    grp_ProjY_fu_312->ap_ready(grp_ProjY_fu_312_ap_ready);
    grp_ProjY_fu_312->ap_ce(ap_var_for_const0);
    grp_ProjY_fu_312->pt_V(grp_ProjY_fu_312_pt_V);
    grp_ProjY_fu_312->phi_V(grp_ProjY_fu_312_phi_V);
    grp_ProjY_fu_312->ap_return(grp_ProjY_fu_312_ap_return);
    grp_ProjY_fu_322 = new ProjY("grp_ProjY_fu_322");
    grp_ProjY_fu_322->ap_clk(ap_clk);
    grp_ProjY_fu_322->ap_rst(ap_rst);
    grp_ProjY_fu_322->ap_start(grp_ProjY_fu_322_ap_start);
    grp_ProjY_fu_322->ap_done(grp_ProjY_fu_322_ap_done);
    grp_ProjY_fu_322->ap_idle(grp_ProjY_fu_322_ap_idle);
    grp_ProjY_fu_322->ap_ready(grp_ProjY_fu_322_ap_ready);
    grp_ProjY_fu_322->ap_ce(ap_var_for_const0);
    grp_ProjY_fu_322->pt_V(grp_ProjY_fu_322_pt_V);
    grp_ProjY_fu_322->phi_V(grp_ProjY_fu_322_phi_V);
    grp_ProjY_fu_322->ap_return(grp_ProjY_fu_322_ap_return);
    jet_hw_mul_mul_17s_17s_32_1_1_U10 = new jet_hw_mul_mul_17s_17s_32_1_1<1,1,17,17,32>("jet_hw_mul_mul_17s_17s_32_1_1_U10");
    jet_hw_mul_mul_17s_17s_32_1_1_U10->din0(mul_ln214_1_fu_706_p0);
    jet_hw_mul_mul_17s_17s_32_1_1_U10->din1(mul_ln214_1_fu_706_p1);
    jet_hw_mul_mul_17s_17s_32_1_1_U10->dout(mul_ln214_1_fu_706_p2);
    jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11 = new jet_hw_mac_muladd_17s_17s_32s_32_1_1<1,1,17,17,32,32>("jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11");
    jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11->din0(grp_fu_712_p0);
    jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11->din1(grp_fu_712_p1);
    jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11->din2(mul_ln214_1_reg_805);
    jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11->dout(grp_fu_712_p3);
    jet_hw_mul_mul_16s_16s_16_1_1_U12 = new jet_hw_mul_mul_16s_16s_16_1_1<1,1,16,16,16>("jet_hw_mul_mul_16s_16s_16_1_1_U12");
    jet_hw_mul_mul_16s_16s_16_1_1_U12->din0(select_ln247_reg_816);
    jet_hw_mul_mul_16s_16s_16_1_1_U12->din1(select_ln891_reg_841);
    jet_hw_mul_mul_16s_16s_16_1_1_U12->dout(a_over_b_V_fu_720_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_V_fu_513_p3);
    sensitive << ( y_V_reg_785 );
    sensitive << ( tmp_1_reg_798 );
    sensitive << ( y_V_1_fu_508_p2 );

    SC_METHOD(thread_add_ln68_fu_667_p2);
    sensitive << ( select_ln895_fu_660_p3 );

    SC_METHOD(thread_and_ln262_fu_621_p2);
    sensitive << ( tmp_reg_791 );
    sensitive << ( icmp_ln895_2_reg_836 );

    SC_METHOD(thread_and_ln887_fu_685_p2);
    sensitive << ( tmp_reg_791 );
    sensitive << ( xor_ln237_fu_680_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_01001);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_01001);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_pp0_stage4);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);

    SC_METHOD(thread_ap_block_pp0_stage5);

    SC_METHOD(thread_ap_block_pp0_stage5_11001);

    SC_METHOD(thread_ap_block_pp0_stage5_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage3_iter1);

    SC_METHOD(thread_ap_block_state11_pp0_stage4_iter1);

    SC_METHOD(thread_ap_block_state12_pp0_stage5_iter1);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state14_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage5_iter0);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state8_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state9_pp0_stage2_iter1);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0_reg );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp0_0to1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp0_1to2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_block_pp0_stage5_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to1 );

    SC_METHOD(thread_atan_table4_address0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_block_pp0_stage5 );
    sensitive << ( zext_ln544_1_fu_597_p1 );

    SC_METHOD(thread_atan_table4_ce0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage5 );
    sensitive << ( ap_block_pp0_stage5_11001 );

    SC_METHOD(thread_grp_ProjX_fu_276_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_ProjX_fu_276_ap_start_reg );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_ProjX_fu_276_phi_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_phi_0_V );
    sensitive << ( jet_phi_2_V );
    sensitive << ( jet_phi_4_V );
    sensitive << ( jet_phi_6_V );
    sensitive << ( jet_phi_8_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjX_fu_276_pt_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_pt_0_V );
    sensitive << ( jet_pt_2_V );
    sensitive << ( jet_pt_4_V );
    sensitive << ( jet_pt_6_V );
    sensitive << ( jet_pt_8_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjX_fu_286_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_ProjX_fu_286_ap_start_reg );

    SC_METHOD(thread_grp_ProjX_fu_286_phi_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_phi_1_V );
    sensitive << ( jet_phi_3_V );
    sensitive << ( jet_phi_5_V );
    sensitive << ( jet_phi_7_V );
    sensitive << ( jet_phi_9_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjX_fu_286_pt_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_pt_1_V );
    sensitive << ( jet_pt_3_V );
    sensitive << ( jet_pt_5_V );
    sensitive << ( jet_pt_7_V );
    sensitive << ( jet_pt_9_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjY_fu_312_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_ProjY_fu_312_ap_start_reg );

    SC_METHOD(thread_grp_ProjY_fu_312_phi_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_phi_0_V );
    sensitive << ( jet_phi_2_V );
    sensitive << ( jet_phi_4_V );
    sensitive << ( jet_phi_6_V );
    sensitive << ( jet_phi_8_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjY_fu_312_pt_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_pt_0_V );
    sensitive << ( jet_pt_2_V );
    sensitive << ( jet_pt_4_V );
    sensitive << ( jet_pt_6_V );
    sensitive << ( jet_pt_8_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjY_fu_322_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_ProjY_fu_322_ap_start_reg );

    SC_METHOD(thread_grp_ProjY_fu_322_phi_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_phi_1_V );
    sensitive << ( jet_phi_3_V );
    sensitive << ( jet_phi_5_V );
    sensitive << ( jet_phi_7_V );
    sensitive << ( jet_phi_9_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_ProjY_fu_322_pt_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( jet_pt_1_V );
    sensitive << ( jet_pt_3_V );
    sensitive << ( jet_pt_5_V );
    sensitive << ( jet_pt_7_V );
    sensitive << ( jet_pt_9_V );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_grp_fu_712_p0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( sext_ln214_fu_573_p1 );

    SC_METHOD(thread_grp_fu_712_p1);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( sext_ln214_fu_573_p1 );

    SC_METHOD(thread_icmp_ln237_fu_491_p2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( or_ln237_fu_487_p2 );

    SC_METHOD(thread_icmp_ln891_fu_551_p2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( tmp_2_fu_541_p4 );

    SC_METHOD(thread_icmp_ln895_1_fu_562_p2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( x_V_3_fu_502_p3 );
    sensitive << ( a_V_fu_513_p3 );

    SC_METHOD(thread_icmp_ln895_2_fu_568_p2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( sub_ln701_19_reg_772 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_icmp_ln895_3_fu_583_p2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( sub_ln701_18_reg_765 );
    sensitive << ( icmp_ln237_reg_810 );

    SC_METHOD(thread_icmp_ln895_fu_519_p2);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( x_V_3_fu_502_p3 );
    sensitive << ( a_V_fu_513_p3 );

    SC_METHOD(thread_inv_table3_address0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( zext_ln544_fu_557_p1 );

    SC_METHOD(thread_inv_table3_ce0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_met_phi_V);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( icmp_ln237_reg_810 );
    sensitive << ( ap_block_pp0_stage1_01001 );
    sensitive << ( select_ln887_fu_690_p3 );

    SC_METHOD(thread_met_phi_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_met_pt2_V);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( grp_fu_712_p3 );
    sensitive << ( ap_block_pp0_stage3_01001 );

    SC_METHOD(thread_met_pt2_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_mul_ln214_1_fu_706_p0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sext_ln214_1_fu_484_p1 );

    SC_METHOD(thread_mul_ln214_1_fu_706_p1);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sext_ln214_1_fu_484_p1 );

    SC_METHOD(thread_or_ln237_fu_487_p2);
    sensitive << ( sub_ln701_18_reg_765 );
    sensitive << ( sub_ln701_19_reg_772 );

    SC_METHOD(thread_select_ln247_1_fu_533_p3);
    sensitive << ( x_V_3_fu_502_p3 );
    sensitive << ( a_V_fu_513_p3 );
    sensitive << ( icmp_ln895_fu_519_p2 );

    SC_METHOD(thread_select_ln247_fu_525_p3);
    sensitive << ( x_V_3_fu_502_p3 );
    sensitive << ( a_V_fu_513_p3 );
    sensitive << ( icmp_ln895_fu_519_p2 );

    SC_METHOD(thread_select_ln260_fu_610_p3);
    sensitive << ( icmp_ln895_1_reg_831 );
    sensitive << ( zext_ln895_fu_601_p1 );
    sensitive << ( sub_ln68_fu_604_p2 );

    SC_METHOD(thread_select_ln262_fu_631_p3);
    sensitive << ( zext_ln260_fu_617_p1 );
    sensitive << ( and_ln262_fu_621_p2 );
    sensitive << ( sub_ln68_1_fu_625_p2 );

    SC_METHOD(thread_select_ln263_fu_653_p3);
    sensitive << ( tmp_1_reg_798 );
    sensitive << ( sext_ln68_fu_649_p1 );
    sensitive << ( zext_ln262_fu_639_p1 );

    SC_METHOD(thread_select_ln264_fu_673_p3);
    sensitive << ( tmp_1_reg_798 );
    sensitive << ( select_ln895_fu_660_p3 );
    sensitive << ( add_ln68_fu_667_p2 );

    SC_METHOD(thread_select_ln887_fu_690_p3);
    sensitive << ( select_ln895_fu_660_p3 );
    sensitive << ( and_ln887_fu_685_p2 );
    sensitive << ( select_ln264_fu_673_p3 );

    SC_METHOD(thread_select_ln891_fu_576_p3);
    sensitive << ( inv_table3_q0 );
    sensitive << ( icmp_ln891_reg_821 );

    SC_METHOD(thread_select_ln895_fu_660_p3);
    sensitive << ( icmp_ln895_3_reg_846 );
    sensitive << ( zext_ln262_fu_639_p1 );
    sensitive << ( select_ln263_fu_653_p3 );

    SC_METHOD(thread_sext_ln214_1_fu_484_p1);
    sensitive << ( sub_ln701_19_reg_772 );

    SC_METHOD(thread_sext_ln214_fu_573_p1);
    sensitive << ( sub_ln701_18_reg_765 );

    SC_METHOD(thread_sext_ln68_fu_649_p1);
    sensitive << ( sub_ln68_2_fu_643_p2 );

    SC_METHOD(thread_sub_ln68_1_fu_625_p2);
    sensitive << ( zext_ln260_fu_617_p1 );

    SC_METHOD(thread_sub_ln68_2_fu_643_p2);
    sensitive << ( select_ln262_fu_631_p3 );

    SC_METHOD(thread_sub_ln68_fu_604_p2);
    sensitive << ( zext_ln895_fu_601_p1 );

    SC_METHOD(thread_sub_ln701_10_fu_404_p2);
    sensitive << ( grp_ProjX_fu_286_ap_return );
    sensitive << ( sub_ln701_8_fu_394_p2 );

    SC_METHOD(thread_sub_ln701_11_fu_410_p2);
    sensitive << ( grp_ProjY_fu_322_ap_return );
    sensitive << ( sub_ln701_9_fu_399_p2 );

    SC_METHOD(thread_sub_ln701_12_fu_416_p2);
    sensitive << ( sub_ln701_10_reg_745 );
    sensitive << ( grp_ProjX_fu_276_ap_return );

    SC_METHOD(thread_sub_ln701_13_fu_421_p2);
    sensitive << ( sub_ln701_11_reg_750 );
    sensitive << ( grp_ProjY_fu_312_ap_return );

    SC_METHOD(thread_sub_ln701_14_fu_426_p2);
    sensitive << ( grp_ProjX_fu_286_ap_return );
    sensitive << ( sub_ln701_12_fu_416_p2 );

    SC_METHOD(thread_sub_ln701_15_fu_432_p2);
    sensitive << ( grp_ProjY_fu_322_ap_return );
    sensitive << ( sub_ln701_13_fu_421_p2 );

    SC_METHOD(thread_sub_ln701_16_fu_438_p2);
    sensitive << ( sub_ln701_14_reg_755 );
    sensitive << ( grp_ProjX_fu_276_ap_return );

    SC_METHOD(thread_sub_ln701_17_fu_443_p2);
    sensitive << ( sub_ln701_15_reg_760 );
    sensitive << ( grp_ProjY_fu_312_ap_return );

    SC_METHOD(thread_sub_ln701_18_fu_448_p2);
    sensitive << ( grp_ProjX_fu_286_ap_return );
    sensitive << ( sub_ln701_16_fu_438_p2 );

    SC_METHOD(thread_sub_ln701_19_fu_454_p2);
    sensitive << ( grp_ProjY_fu_322_ap_return );
    sensitive << ( sub_ln701_17_fu_443_p2 );

    SC_METHOD(thread_sub_ln701_1_fu_354_p2);
    sensitive << ( grp_ProjY_fu_312_ap_return );

    SC_METHOD(thread_sub_ln701_2_fu_360_p2);
    sensitive << ( grp_ProjX_fu_286_ap_return );
    sensitive << ( sub_ln701_fu_348_p2 );

    SC_METHOD(thread_sub_ln701_3_fu_366_p2);
    sensitive << ( grp_ProjY_fu_322_ap_return );
    sensitive << ( sub_ln701_1_fu_354_p2 );

    SC_METHOD(thread_sub_ln701_4_fu_372_p2);
    sensitive << ( sub_ln701_2_reg_725 );
    sensitive << ( grp_ProjX_fu_276_ap_return );

    SC_METHOD(thread_sub_ln701_5_fu_377_p2);
    sensitive << ( sub_ln701_3_reg_730 );
    sensitive << ( grp_ProjY_fu_312_ap_return );

    SC_METHOD(thread_sub_ln701_6_fu_382_p2);
    sensitive << ( grp_ProjX_fu_286_ap_return );
    sensitive << ( sub_ln701_4_fu_372_p2 );

    SC_METHOD(thread_sub_ln701_7_fu_388_p2);
    sensitive << ( grp_ProjY_fu_322_ap_return );
    sensitive << ( sub_ln701_5_fu_377_p2 );

    SC_METHOD(thread_sub_ln701_8_fu_394_p2);
    sensitive << ( sub_ln701_6_reg_735 );
    sensitive << ( grp_ProjX_fu_276_ap_return );

    SC_METHOD(thread_sub_ln701_9_fu_399_p2);
    sensitive << ( sub_ln701_7_reg_740 );
    sensitive << ( grp_ProjY_fu_312_ap_return );

    SC_METHOD(thread_sub_ln701_fu_348_p2);
    sensitive << ( grp_ProjX_fu_276_ap_return );

    SC_METHOD(thread_tmp_2_fu_541_p4);
    sensitive << ( select_ln247_1_fu_533_p3 );

    SC_METHOD(thread_x_V_1_fu_497_p2);
    sensitive << ( x_V_reg_779 );

    SC_METHOD(thread_x_V_3_fu_502_p3);
    sensitive << ( x_V_reg_779 );
    sensitive << ( tmp_reg_791 );
    sensitive << ( x_V_1_fu_497_p2 );

    SC_METHOD(thread_x_V_fu_460_p1);
    sensitive << ( sub_ln701_18_fu_448_p2 );

    SC_METHOD(thread_xor_ln237_fu_680_p2);
    sensitive << ( icmp_ln237_reg_810 );

    SC_METHOD(thread_y_V_1_fu_508_p2);
    sensitive << ( y_V_reg_785 );

    SC_METHOD(thread_y_V_fu_464_p1);
    sensitive << ( sub_ln701_19_fu_454_p2 );

    SC_METHOD(thread_zext_ln260_fu_617_p1);
    sensitive << ( select_ln260_fu_610_p3 );

    SC_METHOD(thread_zext_ln262_fu_639_p1);
    sensitive << ( select_ln262_fu_631_p3 );

    SC_METHOD(thread_zext_ln544_1_fu_597_p1);
    sensitive << ( atan_index_V_reg_851 );

    SC_METHOD(thread_zext_ln544_fu_557_p1);
    sensitive << ( select_ln247_1_fu_533_p3 );

    SC_METHOD(thread_zext_ln895_fu_601_p1);
    sensitive << ( atan_table4_load_reg_861 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage5_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_idle_pp0_1to2 );
    sensitive << ( ap_reset_idle_pp0 );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0_reg = SC_LOGIC_0;
    grp_ProjX_fu_276_ap_start_reg = SC_LOGIC_0;
    grp_ProjX_fu_286_ap_start_reg = SC_LOGIC_0;
    grp_ProjY_fu_312_ap_start_reg = SC_LOGIC_0;
    grp_ProjY_fu_322_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "jet_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, jet_pt_0_V, "(port)jet_pt_0_V");
    sc_trace(mVcdFile, jet_pt_1_V, "(port)jet_pt_1_V");
    sc_trace(mVcdFile, jet_pt_2_V, "(port)jet_pt_2_V");
    sc_trace(mVcdFile, jet_pt_3_V, "(port)jet_pt_3_V");
    sc_trace(mVcdFile, jet_pt_4_V, "(port)jet_pt_4_V");
    sc_trace(mVcdFile, jet_pt_5_V, "(port)jet_pt_5_V");
    sc_trace(mVcdFile, jet_pt_6_V, "(port)jet_pt_6_V");
    sc_trace(mVcdFile, jet_pt_7_V, "(port)jet_pt_7_V");
    sc_trace(mVcdFile, jet_pt_8_V, "(port)jet_pt_8_V");
    sc_trace(mVcdFile, jet_pt_9_V, "(port)jet_pt_9_V");
    sc_trace(mVcdFile, jet_phi_0_V, "(port)jet_phi_0_V");
    sc_trace(mVcdFile, jet_phi_1_V, "(port)jet_phi_1_V");
    sc_trace(mVcdFile, jet_phi_2_V, "(port)jet_phi_2_V");
    sc_trace(mVcdFile, jet_phi_3_V, "(port)jet_phi_3_V");
    sc_trace(mVcdFile, jet_phi_4_V, "(port)jet_phi_4_V");
    sc_trace(mVcdFile, jet_phi_5_V, "(port)jet_phi_5_V");
    sc_trace(mVcdFile, jet_phi_6_V, "(port)jet_phi_6_V");
    sc_trace(mVcdFile, jet_phi_7_V, "(port)jet_phi_7_V");
    sc_trace(mVcdFile, jet_phi_8_V, "(port)jet_phi_8_V");
    sc_trace(mVcdFile, jet_phi_9_V, "(port)jet_phi_9_V");
    sc_trace(mVcdFile, met_pt2_V, "(port)met_pt2_V");
    sc_trace(mVcdFile, met_pt2_V_ap_vld, "(port)met_pt2_V_ap_vld");
    sc_trace(mVcdFile, met_phi_V, "(port)met_phi_V");
    sc_trace(mVcdFile, met_phi_V_ap_vld, "(port)met_phi_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage5, "ap_CS_fsm_pp0_stage5");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage5_iter0, "ap_block_state6_pp0_stage5_iter0");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage5_iter1, "ap_block_state12_pp0_stage5_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage5_11001, "ap_block_pp0_stage5_11001");
    sc_trace(mVcdFile, inv_table3_address0, "inv_table3_address0");
    sc_trace(mVcdFile, inv_table3_ce0, "inv_table3_ce0");
    sc_trace(mVcdFile, inv_table3_q0, "inv_table3_q0");
    sc_trace(mVcdFile, atan_table4_address0, "atan_table4_address0");
    sc_trace(mVcdFile, atan_table4_ce0, "atan_table4_ce0");
    sc_trace(mVcdFile, atan_table4_q0, "atan_table4_q0");
    sc_trace(mVcdFile, sub_ln701_2_fu_360_p2, "sub_ln701_2_fu_360_p2");
    sc_trace(mVcdFile, sub_ln701_2_reg_725, "sub_ln701_2_reg_725");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage3_iter0, "ap_block_state4_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage3_iter1, "ap_block_state10_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, sub_ln701_3_fu_366_p2, "sub_ln701_3_fu_366_p2");
    sc_trace(mVcdFile, sub_ln701_3_reg_730, "sub_ln701_3_reg_730");
    sc_trace(mVcdFile, sub_ln701_6_fu_382_p2, "sub_ln701_6_fu_382_p2");
    sc_trace(mVcdFile, sub_ln701_6_reg_735, "sub_ln701_6_reg_735");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage4_iter0, "ap_block_state5_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage4_iter1, "ap_block_state11_pp0_stage4_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, sub_ln701_7_fu_388_p2, "sub_ln701_7_fu_388_p2");
    sc_trace(mVcdFile, sub_ln701_7_reg_740, "sub_ln701_7_reg_740");
    sc_trace(mVcdFile, sub_ln701_10_fu_404_p2, "sub_ln701_10_fu_404_p2");
    sc_trace(mVcdFile, sub_ln701_10_reg_745, "sub_ln701_10_reg_745");
    sc_trace(mVcdFile, sub_ln701_11_fu_410_p2, "sub_ln701_11_fu_410_p2");
    sc_trace(mVcdFile, sub_ln701_11_reg_750, "sub_ln701_11_reg_750");
    sc_trace(mVcdFile, sub_ln701_14_fu_426_p2, "sub_ln701_14_fu_426_p2");
    sc_trace(mVcdFile, sub_ln701_14_reg_755, "sub_ln701_14_reg_755");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter1, "ap_block_state7_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter2, "ap_block_state13_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, sub_ln701_15_fu_432_p2, "sub_ln701_15_fu_432_p2");
    sc_trace(mVcdFile, sub_ln701_15_reg_760, "sub_ln701_15_reg_760");
    sc_trace(mVcdFile, sub_ln701_18_fu_448_p2, "sub_ln701_18_fu_448_p2");
    sc_trace(mVcdFile, sub_ln701_18_reg_765, "sub_ln701_18_reg_765");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage1_iter0, "ap_block_state2_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage1_iter1, "ap_block_state8_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage1_iter2, "ap_block_state14_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, sub_ln701_19_fu_454_p2, "sub_ln701_19_fu_454_p2");
    sc_trace(mVcdFile, sub_ln701_19_reg_772, "sub_ln701_19_reg_772");
    sc_trace(mVcdFile, x_V_fu_460_p1, "x_V_fu_460_p1");
    sc_trace(mVcdFile, x_V_reg_779, "x_V_reg_779");
    sc_trace(mVcdFile, y_V_fu_464_p1, "y_V_fu_464_p1");
    sc_trace(mVcdFile, y_V_reg_785, "y_V_reg_785");
    sc_trace(mVcdFile, tmp_reg_791, "tmp_reg_791");
    sc_trace(mVcdFile, tmp_1_reg_798, "tmp_1_reg_798");
    sc_trace(mVcdFile, mul_ln214_1_fu_706_p2, "mul_ln214_1_fu_706_p2");
    sc_trace(mVcdFile, mul_ln214_1_reg_805, "mul_ln214_1_reg_805");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage2_iter0, "ap_block_state3_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage2_iter1, "ap_block_state9_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, icmp_ln237_fu_491_p2, "icmp_ln237_fu_491_p2");
    sc_trace(mVcdFile, icmp_ln237_reg_810, "icmp_ln237_reg_810");
    sc_trace(mVcdFile, select_ln247_fu_525_p3, "select_ln247_fu_525_p3");
    sc_trace(mVcdFile, select_ln247_reg_816, "select_ln247_reg_816");
    sc_trace(mVcdFile, icmp_ln891_fu_551_p2, "icmp_ln891_fu_551_p2");
    sc_trace(mVcdFile, icmp_ln891_reg_821, "icmp_ln891_reg_821");
    sc_trace(mVcdFile, icmp_ln895_1_fu_562_p2, "icmp_ln895_1_fu_562_p2");
    sc_trace(mVcdFile, icmp_ln895_1_reg_831, "icmp_ln895_1_reg_831");
    sc_trace(mVcdFile, icmp_ln895_2_fu_568_p2, "icmp_ln895_2_fu_568_p2");
    sc_trace(mVcdFile, icmp_ln895_2_reg_836, "icmp_ln895_2_reg_836");
    sc_trace(mVcdFile, select_ln891_fu_576_p3, "select_ln891_fu_576_p3");
    sc_trace(mVcdFile, select_ln891_reg_841, "select_ln891_reg_841");
    sc_trace(mVcdFile, icmp_ln895_3_fu_583_p2, "icmp_ln895_3_fu_583_p2");
    sc_trace(mVcdFile, icmp_ln895_3_reg_846, "icmp_ln895_3_reg_846");
    sc_trace(mVcdFile, atan_index_V_reg_851, "atan_index_V_reg_851");
    sc_trace(mVcdFile, atan_table4_load_reg_861, "atan_table4_load_reg_861");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0_reg, "ap_enable_reg_pp0_iter0_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage5_subdone, "ap_block_pp0_stage5_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, grp_ProjX_fu_276_ap_start, "grp_ProjX_fu_276_ap_start");
    sc_trace(mVcdFile, grp_ProjX_fu_276_ap_done, "grp_ProjX_fu_276_ap_done");
    sc_trace(mVcdFile, grp_ProjX_fu_276_ap_idle, "grp_ProjX_fu_276_ap_idle");
    sc_trace(mVcdFile, grp_ProjX_fu_276_ap_ready, "grp_ProjX_fu_276_ap_ready");
    sc_trace(mVcdFile, grp_ProjX_fu_276_pt_V, "grp_ProjX_fu_276_pt_V");
    sc_trace(mVcdFile, grp_ProjX_fu_276_phi_V, "grp_ProjX_fu_276_phi_V");
    sc_trace(mVcdFile, grp_ProjX_fu_276_ap_return, "grp_ProjX_fu_276_ap_return");
    sc_trace(mVcdFile, grp_ProjX_fu_286_ap_start, "grp_ProjX_fu_286_ap_start");
    sc_trace(mVcdFile, grp_ProjX_fu_286_ap_done, "grp_ProjX_fu_286_ap_done");
    sc_trace(mVcdFile, grp_ProjX_fu_286_ap_idle, "grp_ProjX_fu_286_ap_idle");
    sc_trace(mVcdFile, grp_ProjX_fu_286_ap_ready, "grp_ProjX_fu_286_ap_ready");
    sc_trace(mVcdFile, grp_ProjX_fu_286_pt_V, "grp_ProjX_fu_286_pt_V");
    sc_trace(mVcdFile, grp_ProjX_fu_286_phi_V, "grp_ProjX_fu_286_phi_V");
    sc_trace(mVcdFile, grp_ProjX_fu_286_ap_return, "grp_ProjX_fu_286_ap_return");
    sc_trace(mVcdFile, grp_ProjY_fu_312_ap_start, "grp_ProjY_fu_312_ap_start");
    sc_trace(mVcdFile, grp_ProjY_fu_312_ap_done, "grp_ProjY_fu_312_ap_done");
    sc_trace(mVcdFile, grp_ProjY_fu_312_ap_idle, "grp_ProjY_fu_312_ap_idle");
    sc_trace(mVcdFile, grp_ProjY_fu_312_ap_ready, "grp_ProjY_fu_312_ap_ready");
    sc_trace(mVcdFile, grp_ProjY_fu_312_pt_V, "grp_ProjY_fu_312_pt_V");
    sc_trace(mVcdFile, grp_ProjY_fu_312_phi_V, "grp_ProjY_fu_312_phi_V");
    sc_trace(mVcdFile, grp_ProjY_fu_312_ap_return, "grp_ProjY_fu_312_ap_return");
    sc_trace(mVcdFile, grp_ProjY_fu_322_ap_start, "grp_ProjY_fu_322_ap_start");
    sc_trace(mVcdFile, grp_ProjY_fu_322_ap_done, "grp_ProjY_fu_322_ap_done");
    sc_trace(mVcdFile, grp_ProjY_fu_322_ap_idle, "grp_ProjY_fu_322_ap_idle");
    sc_trace(mVcdFile, grp_ProjY_fu_322_ap_ready, "grp_ProjY_fu_322_ap_ready");
    sc_trace(mVcdFile, grp_ProjY_fu_322_pt_V, "grp_ProjY_fu_322_pt_V");
    sc_trace(mVcdFile, grp_ProjY_fu_322_phi_V, "grp_ProjY_fu_322_phi_V");
    sc_trace(mVcdFile, grp_ProjY_fu_322_ap_return, "grp_ProjY_fu_322_ap_return");
    sc_trace(mVcdFile, grp_ProjX_fu_276_ap_start_reg, "grp_ProjX_fu_276_ap_start_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, ap_block_pp0_stage4, "ap_block_pp0_stage4");
    sc_trace(mVcdFile, ap_block_pp0_stage5, "ap_block_pp0_stage5");
    sc_trace(mVcdFile, grp_ProjX_fu_286_ap_start_reg, "grp_ProjX_fu_286_ap_start_reg");
    sc_trace(mVcdFile, grp_ProjY_fu_312_ap_start_reg, "grp_ProjY_fu_312_ap_start_reg");
    sc_trace(mVcdFile, grp_ProjY_fu_322_ap_start_reg, "grp_ProjY_fu_322_ap_start_reg");
    sc_trace(mVcdFile, zext_ln544_fu_557_p1, "zext_ln544_fu_557_p1");
    sc_trace(mVcdFile, zext_ln544_1_fu_597_p1, "zext_ln544_1_fu_597_p1");
    sc_trace(mVcdFile, grp_fu_712_p3, "grp_fu_712_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage3_01001, "ap_block_pp0_stage3_01001");
    sc_trace(mVcdFile, ap_block_pp0_stage1_01001, "ap_block_pp0_stage1_01001");
    sc_trace(mVcdFile, sub_ln701_fu_348_p2, "sub_ln701_fu_348_p2");
    sc_trace(mVcdFile, sub_ln701_1_fu_354_p2, "sub_ln701_1_fu_354_p2");
    sc_trace(mVcdFile, sub_ln701_4_fu_372_p2, "sub_ln701_4_fu_372_p2");
    sc_trace(mVcdFile, sub_ln701_5_fu_377_p2, "sub_ln701_5_fu_377_p2");
    sc_trace(mVcdFile, sub_ln701_8_fu_394_p2, "sub_ln701_8_fu_394_p2");
    sc_trace(mVcdFile, sub_ln701_9_fu_399_p2, "sub_ln701_9_fu_399_p2");
    sc_trace(mVcdFile, sub_ln701_12_fu_416_p2, "sub_ln701_12_fu_416_p2");
    sc_trace(mVcdFile, sub_ln701_13_fu_421_p2, "sub_ln701_13_fu_421_p2");
    sc_trace(mVcdFile, sub_ln701_16_fu_438_p2, "sub_ln701_16_fu_438_p2");
    sc_trace(mVcdFile, sub_ln701_17_fu_443_p2, "sub_ln701_17_fu_443_p2");
    sc_trace(mVcdFile, or_ln237_fu_487_p2, "or_ln237_fu_487_p2");
    sc_trace(mVcdFile, x_V_1_fu_497_p2, "x_V_1_fu_497_p2");
    sc_trace(mVcdFile, y_V_1_fu_508_p2, "y_V_1_fu_508_p2");
    sc_trace(mVcdFile, x_V_3_fu_502_p3, "x_V_3_fu_502_p3");
    sc_trace(mVcdFile, a_V_fu_513_p3, "a_V_fu_513_p3");
    sc_trace(mVcdFile, icmp_ln895_fu_519_p2, "icmp_ln895_fu_519_p2");
    sc_trace(mVcdFile, select_ln247_1_fu_533_p3, "select_ln247_1_fu_533_p3");
    sc_trace(mVcdFile, tmp_2_fu_541_p4, "tmp_2_fu_541_p4");
    sc_trace(mVcdFile, a_over_b_V_fu_720_p2, "a_over_b_V_fu_720_p2");
    sc_trace(mVcdFile, zext_ln895_fu_601_p1, "zext_ln895_fu_601_p1");
    sc_trace(mVcdFile, sub_ln68_fu_604_p2, "sub_ln68_fu_604_p2");
    sc_trace(mVcdFile, select_ln260_fu_610_p3, "select_ln260_fu_610_p3");
    sc_trace(mVcdFile, zext_ln260_fu_617_p1, "zext_ln260_fu_617_p1");
    sc_trace(mVcdFile, and_ln262_fu_621_p2, "and_ln262_fu_621_p2");
    sc_trace(mVcdFile, sub_ln68_1_fu_625_p2, "sub_ln68_1_fu_625_p2");
    sc_trace(mVcdFile, select_ln262_fu_631_p3, "select_ln262_fu_631_p3");
    sc_trace(mVcdFile, sub_ln68_2_fu_643_p2, "sub_ln68_2_fu_643_p2");
    sc_trace(mVcdFile, sext_ln68_fu_649_p1, "sext_ln68_fu_649_p1");
    sc_trace(mVcdFile, zext_ln262_fu_639_p1, "zext_ln262_fu_639_p1");
    sc_trace(mVcdFile, select_ln263_fu_653_p3, "select_ln263_fu_653_p3");
    sc_trace(mVcdFile, select_ln895_fu_660_p3, "select_ln895_fu_660_p3");
    sc_trace(mVcdFile, add_ln68_fu_667_p2, "add_ln68_fu_667_p2");
    sc_trace(mVcdFile, xor_ln237_fu_680_p2, "xor_ln237_fu_680_p2");
    sc_trace(mVcdFile, and_ln887_fu_685_p2, "and_ln887_fu_685_p2");
    sc_trace(mVcdFile, select_ln264_fu_673_p3, "select_ln264_fu_673_p3");
    sc_trace(mVcdFile, select_ln887_fu_690_p3, "select_ln887_fu_690_p3");
    sc_trace(mVcdFile, mul_ln214_1_fu_706_p0, "mul_ln214_1_fu_706_p0");
    sc_trace(mVcdFile, sext_ln214_1_fu_484_p1, "sext_ln214_1_fu_484_p1");
    sc_trace(mVcdFile, mul_ln214_1_fu_706_p1, "mul_ln214_1_fu_706_p1");
    sc_trace(mVcdFile, grp_fu_712_p0, "grp_fu_712_p0");
    sc_trace(mVcdFile, sext_ln214_fu_573_p1, "sext_ln214_fu_573_p1");
    sc_trace(mVcdFile, grp_fu_712_p1, "grp_fu_712_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_idle_pp0_1to2, "ap_idle_pp0_1to2");
    sc_trace(mVcdFile, ap_idle_pp0_0to1, "ap_idle_pp0_0to1");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("jet_hw.hdltvin.dat");
    mHdltvoutHandle.open("jet_hw.hdltvout.dat");
}

jet_hw::~jet_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete inv_table3_U;
    delete atan_table4_U;
    delete grp_ProjX_fu_276;
    delete grp_ProjX_fu_286;
    delete grp_ProjY_fu_312;
    delete grp_ProjY_fu_322;
    delete jet_hw_mul_mul_17s_17s_32_1_1_U10;
    delete jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11;
    delete jet_hw_mul_mul_16s_16s_16_1_1_U12;
}

void jet_hw::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void jet_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
            ap_enable_reg_pp0_iter0_reg = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage5_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage5_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && 
                    esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_ProjX_fu_276_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
            grp_ProjX_fu_276_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_ProjX_fu_276_ap_ready.read())) {
            grp_ProjX_fu_276_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_ProjX_fu_286_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
            grp_ProjX_fu_286_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_ProjX_fu_286_ap_ready.read())) {
            grp_ProjX_fu_286_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_ProjY_fu_312_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
            grp_ProjY_fu_312_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_ProjY_fu_312_ap_ready.read())) {
            grp_ProjY_fu_312_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_ProjY_fu_322_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)))) {
            grp_ProjY_fu_322_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_ProjY_fu_322_ap_ready.read())) {
            grp_ProjY_fu_322_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln237_reg_810.read(), ap_const_lv1_0))) {
        atan_index_V_reg_851 = a_over_b_V_fu_720_p2.read().range(15, 9);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln237_reg_810.read(), ap_const_lv1_0))) {
        atan_table4_load_reg_861 = atan_table4_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        icmp_ln237_reg_810 = icmp_ln237_fu_491_p2.read();
        icmp_ln891_reg_821 = icmp_ln891_fu_551_p2.read();
        icmp_ln895_1_reg_831 = icmp_ln895_1_fu_562_p2.read();
        icmp_ln895_2_reg_836 = icmp_ln895_2_fu_568_p2.read();
        mul_ln214_1_reg_805 = mul_ln214_1_fu_706_p2.read();
        select_ln247_reg_816 = select_ln247_fu_525_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln237_reg_810.read(), ap_const_lv1_0))) {
        icmp_ln895_3_reg_846 = icmp_ln895_3_fu_583_p2.read();
        select_ln891_reg_841 = select_ln891_fu_576_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0))) {
        sub_ln701_10_reg_745 = sub_ln701_10_fu_404_p2.read();
        sub_ln701_11_reg_750 = sub_ln701_11_fu_410_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        sub_ln701_14_reg_755 = sub_ln701_14_fu_426_p2.read();
        sub_ln701_15_reg_760 = sub_ln701_15_fu_432_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        sub_ln701_18_reg_765 = sub_ln701_18_fu_448_p2.read();
        sub_ln701_19_reg_772 = sub_ln701_19_fu_454_p2.read();
        tmp_1_reg_798 = sub_ln701_19_fu_454_p2.read().range(16, 16);
        tmp_reg_791 = sub_ln701_18_fu_448_p2.read().range(16, 16);
        x_V_reg_779 = x_V_fu_460_p1.read();
        y_V_reg_785 = y_V_fu_464_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        sub_ln701_2_reg_725 = sub_ln701_2_fu_360_p2.read();
        sub_ln701_3_reg_730 = sub_ln701_3_fu_366_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0))) {
        sub_ln701_6_reg_735 = sub_ln701_6_fu_382_p2.read();
        sub_ln701_7_reg_740 = sub_ln701_7_fu_388_p2.read();
    }
}

void jet_hw::thread_a_V_fu_513_p3() {
    a_V_fu_513_p3 = (!tmp_1_reg_798.read()[0].is_01())? sc_lv<16>(): ((tmp_1_reg_798.read()[0].to_bool())? y_V_1_fu_508_p2.read(): y_V_reg_785.read());
}

void jet_hw::thread_add_ln68_fu_667_p2() {
    add_ln68_fu_667_p2 = (!ap_const_lv11_600.is_01() || !select_ln895_fu_660_p3.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_600) + sc_biguint<11>(select_ln895_fu_660_p3.read()));
}

void jet_hw::thread_and_ln262_fu_621_p2() {
    and_ln262_fu_621_p2 = (tmp_reg_791.read() & icmp_ln895_2_reg_836.read());
}

void jet_hw::thread_and_ln887_fu_685_p2() {
    and_ln887_fu_685_p2 = (tmp_reg_791.read() & xor_ln237_fu_680_p2.read());
}

void jet_hw::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void jet_hw::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[1];
}

void jet_hw::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[2];
}

void jet_hw::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[3];
}

void jet_hw::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[4];
}

void jet_hw::thread_ap_CS_fsm_pp0_stage5() {
    ap_CS_fsm_pp0_stage5 = ap_CS_fsm.read()[5];
}

void jet_hw::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()));
}

void jet_hw::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()));
}

void jet_hw::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage1_01001() {
    ap_block_pp0_stage1_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage3_01001() {
    ap_block_pp0_stage3_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage4() {
    ap_block_pp0_stage4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage5() {
    ap_block_pp0_stage5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage5_11001() {
    ap_block_pp0_stage5_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_pp0_stage5_subdone() {
    ap_block_pp0_stage5_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state10_pp0_stage3_iter1() {
    ap_block_state10_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state11_pp0_stage4_iter1() {
    ap_block_state11_pp0_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state12_pp0_stage5_iter1() {
    ap_block_state12_pp0_stage5_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state13_pp0_stage0_iter2() {
    ap_block_state13_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state14_pp0_stage1_iter2() {
    ap_block_state14_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void jet_hw::thread_ap_block_state2_pp0_stage1_iter0() {
    ap_block_state2_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state3_pp0_stage2_iter0() {
    ap_block_state3_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state4_pp0_stage3_iter0() {
    ap_block_state4_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state5_pp0_stage4_iter0() {
    ap_block_state5_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state6_pp0_stage5_iter0() {
    ap_block_state6_pp0_stage5_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state7_pp0_stage0_iter1() {
    ap_block_state7_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state8_pp0_stage1_iter1() {
    ap_block_state8_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_block_state9_pp0_stage2_iter1() {
    ap_block_state9_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void jet_hw::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void jet_hw::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void jet_hw::thread_ap_enable_reg_pp0_iter0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read())) {
        ap_enable_reg_pp0_iter0 = ap_start.read();
    } else {
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg.read();
    }
}

void jet_hw::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void jet_hw::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void jet_hw::thread_ap_idle_pp0_0to1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0_0to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to1 = ap_const_logic_0;
    }
}

void jet_hw::thread_ap_idle_pp0_1to2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0_1to2 = ap_const_logic_1;
    } else {
        ap_idle_pp0_1to2 = ap_const_logic_0;
    }
}

void jet_hw::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void jet_hw::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to1.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void jet_hw::thread_atan_table4_address0() {
    atan_table4_address0 =  (sc_lv<7>) (zext_ln544_1_fu_597_p1.read());
}

void jet_hw::thread_atan_table4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage5.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage5_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        atan_table4_ce0 = ap_const_logic_1;
    } else {
        atan_table4_ce0 = ap_const_logic_0;
    }
}

void jet_hw::thread_grp_ProjX_fu_276_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_ProjX_fu_276_ap_start = ap_const_logic_1;
    } else {
        grp_ProjX_fu_276_ap_start = grp_ProjX_fu_276_ap_start_reg.read();
    }
}

void jet_hw::thread_grp_ProjX_fu_276_phi_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_phi_V = jet_phi_8_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_phi_V = jet_phi_6_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_phi_V = jet_phi_4_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_phi_V = jet_phi_2_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_phi_V = jet_phi_0_V.read();
        } else {
            grp_ProjX_fu_276_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        grp_ProjX_fu_276_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjX_fu_276_pt_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_pt_V = jet_pt_8_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_pt_V = jet_pt_6_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_pt_V = jet_pt_4_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_pt_V = jet_pt_2_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_276_pt_V = jet_pt_0_V.read();
        } else {
            grp_ProjX_fu_276_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        grp_ProjX_fu_276_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjX_fu_286_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_ProjX_fu_286_ap_start = ap_const_logic_1;
    } else {
        grp_ProjX_fu_286_ap_start = grp_ProjX_fu_286_ap_start_reg.read();
    }
}

void jet_hw::thread_grp_ProjX_fu_286_phi_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_phi_V = jet_phi_9_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_phi_V = jet_phi_7_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_phi_V = jet_phi_5_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_phi_V = jet_phi_3_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_phi_V = jet_phi_1_V.read();
        } else {
            grp_ProjX_fu_286_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        grp_ProjX_fu_286_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjX_fu_286_pt_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_pt_V = jet_pt_9_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_pt_V = jet_pt_7_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_pt_V = jet_pt_5_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_pt_V = jet_pt_3_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjX_fu_286_pt_V = jet_pt_1_V.read();
        } else {
            grp_ProjX_fu_286_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        grp_ProjX_fu_286_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjY_fu_312_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_ProjY_fu_312_ap_start = ap_const_logic_1;
    } else {
        grp_ProjY_fu_312_ap_start = grp_ProjY_fu_312_ap_start_reg.read();
    }
}

void jet_hw::thread_grp_ProjY_fu_312_phi_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_phi_V = jet_phi_8_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_phi_V = jet_phi_6_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_phi_V = jet_phi_4_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_phi_V = jet_phi_2_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_phi_V = jet_phi_0_V.read();
        } else {
            grp_ProjY_fu_312_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        grp_ProjY_fu_312_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjY_fu_312_pt_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_pt_V = jet_pt_8_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_pt_V = jet_pt_6_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_pt_V = jet_pt_4_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_pt_V = jet_pt_2_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_312_pt_V = jet_pt_0_V.read();
        } else {
            grp_ProjY_fu_312_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        grp_ProjY_fu_312_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjY_fu_322_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_ProjY_fu_322_ap_start = ap_const_logic_1;
    } else {
        grp_ProjY_fu_322_ap_start = grp_ProjY_fu_322_ap_start_reg.read();
    }
}

void jet_hw::thread_grp_ProjY_fu_322_phi_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_phi_V = jet_phi_9_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_phi_V = jet_phi_7_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_phi_V = jet_phi_5_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_phi_V = jet_phi_3_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_phi_V = jet_phi_1_V.read();
        } else {
            grp_ProjY_fu_322_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        grp_ProjY_fu_322_phi_V =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_ProjY_fu_322_pt_V() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_pt_V = jet_pt_9_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_pt_V = jet_pt_7_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_pt_V = jet_pt_5_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_pt_V = jet_pt_3_V.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            grp_ProjY_fu_322_pt_V = jet_pt_1_V.read();
        } else {
            grp_ProjY_fu_322_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        grp_ProjY_fu_322_pt_V =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void jet_hw::thread_grp_fu_712_p0() {
    grp_fu_712_p0 =  (sc_lv<17>) (sext_ln214_fu_573_p1.read());
}

void jet_hw::thread_grp_fu_712_p1() {
    grp_fu_712_p1 =  (sc_lv<17>) (sext_ln214_fu_573_p1.read());
}

void jet_hw::thread_icmp_ln237_fu_491_p2() {
    icmp_ln237_fu_491_p2 = (!or_ln237_fu_487_p2.read().is_01() || !ap_const_lv17_0.is_01())? sc_lv<1>(): sc_lv<1>(or_ln237_fu_487_p2.read() == ap_const_lv17_0);
}

void jet_hw::thread_icmp_ln891_fu_551_p2() {
    icmp_ln891_fu_551_p2 = (!tmp_2_fu_541_p4.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_541_p4.read() != ap_const_lv4_0);
}

void jet_hw::thread_icmp_ln895_1_fu_562_p2() {
    icmp_ln895_1_fu_562_p2 = (!a_V_fu_513_p3.read().is_01() || !x_V_3_fu_502_p3.read().is_01())? sc_lv<1>(): (sc_biguint<16>(a_V_fu_513_p3.read()) > sc_biguint<16>(x_V_3_fu_502_p3.read()));
}

void jet_hw::thread_icmp_ln895_2_fu_568_p2() {
    icmp_ln895_2_fu_568_p2 = (!sub_ln701_19_reg_772.read().is_01() || !ap_const_lv17_0.is_01())? sc_lv<1>(): (sc_bigint<17>(sub_ln701_19_reg_772.read()) > sc_bigint<17>(ap_const_lv17_0));
}

void jet_hw::thread_icmp_ln895_3_fu_583_p2() {
    icmp_ln895_3_fu_583_p2 = (!sub_ln701_18_reg_765.read().is_01() || !ap_const_lv17_0.is_01())? sc_lv<1>(): (sc_bigint<17>(sub_ln701_18_reg_765.read()) > sc_bigint<17>(ap_const_lv17_0));
}

void jet_hw::thread_icmp_ln895_fu_519_p2() {
    icmp_ln895_fu_519_p2 = (!x_V_3_fu_502_p3.read().is_01() || !a_V_fu_513_p3.read().is_01())? sc_lv<1>(): (sc_biguint<16>(x_V_3_fu_502_p3.read()) > sc_biguint<16>(a_V_fu_513_p3.read()));
}

void jet_hw::thread_inv_table3_address0() {
    inv_table3_address0 =  (sc_lv<12>) (zext_ln544_fu_557_p1.read());
}

void jet_hw::thread_inv_table3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        inv_table3_ce0 = ap_const_logic_1;
    } else {
        inv_table3_ce0 = ap_const_logic_0;
    }
}

void jet_hw::thread_met_phi_V() {
    met_phi_V = (!icmp_ln237_reg_810.read()[0].is_01())? sc_lv<11>(): ((icmp_ln237_reg_810.read()[0].to_bool())? ap_const_lv11_0: select_ln887_fu_690_p3.read());
}

void jet_hw::thread_met_phi_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        met_phi_V_ap_vld = ap_const_logic_1;
    } else {
        met_phi_V_ap_vld = ap_const_logic_0;
    }
}

void jet_hw::thread_met_pt2_V() {
    met_pt2_V = grp_fu_712_p3.read();
}

void jet_hw::thread_met_pt2_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        met_pt2_V_ap_vld = ap_const_logic_1;
    } else {
        met_pt2_V_ap_vld = ap_const_logic_0;
    }
}

void jet_hw::thread_mul_ln214_1_fu_706_p0() {
    mul_ln214_1_fu_706_p0 =  (sc_lv<17>) (sext_ln214_1_fu_484_p1.read());
}

void jet_hw::thread_mul_ln214_1_fu_706_p1() {
    mul_ln214_1_fu_706_p1 =  (sc_lv<17>) (sext_ln214_1_fu_484_p1.read());
}

void jet_hw::thread_or_ln237_fu_487_p2() {
    or_ln237_fu_487_p2 = (sub_ln701_18_reg_765.read() | sub_ln701_19_reg_772.read());
}

void jet_hw::thread_select_ln247_1_fu_533_p3() {
    select_ln247_1_fu_533_p3 = (!icmp_ln895_fu_519_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln895_fu_519_p2.read()[0].to_bool())? x_V_3_fu_502_p3.read(): a_V_fu_513_p3.read());
}

void jet_hw::thread_select_ln247_fu_525_p3() {
    select_ln247_fu_525_p3 = (!icmp_ln895_fu_519_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln895_fu_519_p2.read()[0].to_bool())? a_V_fu_513_p3.read(): x_V_3_fu_502_p3.read());
}

void jet_hw::thread_select_ln260_fu_610_p3() {
    select_ln260_fu_610_p3 = (!icmp_ln895_1_reg_831.read()[0].is_01())? sc_lv<9>(): ((icmp_ln895_1_reg_831.read()[0].to_bool())? sub_ln68_fu_604_p2.read(): zext_ln895_fu_601_p1.read());
}

void jet_hw::thread_select_ln262_fu_631_p3() {
    select_ln262_fu_631_p3 = (!and_ln262_fu_621_p2.read()[0].is_01())? sc_lv<10>(): ((and_ln262_fu_621_p2.read()[0].to_bool())? sub_ln68_1_fu_625_p2.read(): zext_ln260_fu_617_p1.read());
}

void jet_hw::thread_select_ln263_fu_653_p3() {
    select_ln263_fu_653_p3 = (!tmp_1_reg_798.read()[0].is_01())? sc_lv<11>(): ((tmp_1_reg_798.read()[0].to_bool())? sext_ln68_fu_649_p1.read(): zext_ln262_fu_639_p1.read());
}

void jet_hw::thread_select_ln264_fu_673_p3() {
    select_ln264_fu_673_p3 = (!tmp_1_reg_798.read()[0].is_01())? sc_lv<11>(): ((tmp_1_reg_798.read()[0].to_bool())? add_ln68_fu_667_p2.read(): select_ln895_fu_660_p3.read());
}

void jet_hw::thread_select_ln887_fu_690_p3() {
    select_ln887_fu_690_p3 = (!and_ln887_fu_685_p2.read()[0].is_01())? sc_lv<11>(): ((and_ln887_fu_685_p2.read()[0].to_bool())? select_ln264_fu_673_p3.read(): select_ln895_fu_660_p3.read());
}

void jet_hw::thread_select_ln891_fu_576_p3() {
    select_ln891_fu_576_p3 = (!icmp_ln891_reg_821.read()[0].is_01())? sc_lv<16>(): ((icmp_ln891_reg_821.read()[0].to_bool())? ap_const_lv16_1: inv_table3_q0.read());
}

void jet_hw::thread_select_ln895_fu_660_p3() {
    select_ln895_fu_660_p3 = (!icmp_ln895_3_reg_846.read()[0].is_01())? sc_lv<11>(): ((icmp_ln895_3_reg_846.read()[0].to_bool())? select_ln263_fu_653_p3.read(): zext_ln262_fu_639_p1.read());
}

void jet_hw::thread_sext_ln214_1_fu_484_p1() {
    sext_ln214_1_fu_484_p1 = esl_sext<32,17>(sub_ln701_19_reg_772.read());
}

void jet_hw::thread_sext_ln214_fu_573_p1() {
    sext_ln214_fu_573_p1 = esl_sext<32,17>(sub_ln701_18_reg_765.read());
}

void jet_hw::thread_sext_ln68_fu_649_p1() {
    sext_ln68_fu_649_p1 = esl_sext<11,10>(sub_ln68_2_fu_643_p2.read());
}

void jet_hw::thread_sub_ln68_1_fu_625_p2() {
    sub_ln68_1_fu_625_p2 = (!ap_const_lv10_200.is_01() || !zext_ln260_fu_617_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_200) - sc_biguint<10>(zext_ln260_fu_617_p1.read()));
}

void jet_hw::thread_sub_ln68_2_fu_643_p2() {
    sub_ln68_2_fu_643_p2 = (!ap_const_lv10_0.is_01() || !select_ln262_fu_631_p3.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_0) - sc_biguint<10>(select_ln262_fu_631_p3.read()));
}

void jet_hw::thread_sub_ln68_fu_604_p2() {
    sub_ln68_fu_604_p2 = (!ap_const_lv9_100.is_01() || !zext_ln895_fu_601_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_100) - sc_biguint<9>(zext_ln895_fu_601_p1.read()));
}

void jet_hw::thread_sub_ln701_10_fu_404_p2() {
    sub_ln701_10_fu_404_p2 = (!sub_ln701_8_fu_394_p2.read().is_01() || !grp_ProjX_fu_286_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_8_fu_394_p2.read()) - sc_biguint<17>(grp_ProjX_fu_286_ap_return.read()));
}

void jet_hw::thread_sub_ln701_11_fu_410_p2() {
    sub_ln701_11_fu_410_p2 = (!sub_ln701_9_fu_399_p2.read().is_01() || !grp_ProjY_fu_322_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_9_fu_399_p2.read()) - sc_biguint<17>(grp_ProjY_fu_322_ap_return.read()));
}

void jet_hw::thread_sub_ln701_12_fu_416_p2() {
    sub_ln701_12_fu_416_p2 = (!sub_ln701_10_reg_745.read().is_01() || !grp_ProjX_fu_276_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_10_reg_745.read()) - sc_biguint<17>(grp_ProjX_fu_276_ap_return.read()));
}

void jet_hw::thread_sub_ln701_13_fu_421_p2() {
    sub_ln701_13_fu_421_p2 = (!sub_ln701_11_reg_750.read().is_01() || !grp_ProjY_fu_312_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_11_reg_750.read()) - sc_biguint<17>(grp_ProjY_fu_312_ap_return.read()));
}

void jet_hw::thread_sub_ln701_14_fu_426_p2() {
    sub_ln701_14_fu_426_p2 = (!sub_ln701_12_fu_416_p2.read().is_01() || !grp_ProjX_fu_286_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_12_fu_416_p2.read()) - sc_biguint<17>(grp_ProjX_fu_286_ap_return.read()));
}

void jet_hw::thread_sub_ln701_15_fu_432_p2() {
    sub_ln701_15_fu_432_p2 = (!sub_ln701_13_fu_421_p2.read().is_01() || !grp_ProjY_fu_322_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_13_fu_421_p2.read()) - sc_biguint<17>(grp_ProjY_fu_322_ap_return.read()));
}

void jet_hw::thread_sub_ln701_16_fu_438_p2() {
    sub_ln701_16_fu_438_p2 = (!sub_ln701_14_reg_755.read().is_01() || !grp_ProjX_fu_276_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_14_reg_755.read()) - sc_biguint<17>(grp_ProjX_fu_276_ap_return.read()));
}

void jet_hw::thread_sub_ln701_17_fu_443_p2() {
    sub_ln701_17_fu_443_p2 = (!sub_ln701_15_reg_760.read().is_01() || !grp_ProjY_fu_312_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_15_reg_760.read()) - sc_biguint<17>(grp_ProjY_fu_312_ap_return.read()));
}

void jet_hw::thread_sub_ln701_18_fu_448_p2() {
    sub_ln701_18_fu_448_p2 = (!sub_ln701_16_fu_438_p2.read().is_01() || !grp_ProjX_fu_286_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_16_fu_438_p2.read()) - sc_biguint<17>(grp_ProjX_fu_286_ap_return.read()));
}

void jet_hw::thread_sub_ln701_19_fu_454_p2() {
    sub_ln701_19_fu_454_p2 = (!sub_ln701_17_fu_443_p2.read().is_01() || !grp_ProjY_fu_322_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_17_fu_443_p2.read()) - sc_biguint<17>(grp_ProjY_fu_322_ap_return.read()));
}

void jet_hw::thread_sub_ln701_1_fu_354_p2() {
    sub_ln701_1_fu_354_p2 = (!ap_const_lv17_0.is_01() || !grp_ProjY_fu_312_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(grp_ProjY_fu_312_ap_return.read()));
}

void jet_hw::thread_sub_ln701_2_fu_360_p2() {
    sub_ln701_2_fu_360_p2 = (!sub_ln701_fu_348_p2.read().is_01() || !grp_ProjX_fu_286_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_fu_348_p2.read()) - sc_biguint<17>(grp_ProjX_fu_286_ap_return.read()));
}

void jet_hw::thread_sub_ln701_3_fu_366_p2() {
    sub_ln701_3_fu_366_p2 = (!sub_ln701_1_fu_354_p2.read().is_01() || !grp_ProjY_fu_322_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_1_fu_354_p2.read()) - sc_biguint<17>(grp_ProjY_fu_322_ap_return.read()));
}

void jet_hw::thread_sub_ln701_4_fu_372_p2() {
    sub_ln701_4_fu_372_p2 = (!sub_ln701_2_reg_725.read().is_01() || !grp_ProjX_fu_276_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_2_reg_725.read()) - sc_biguint<17>(grp_ProjX_fu_276_ap_return.read()));
}

void jet_hw::thread_sub_ln701_5_fu_377_p2() {
    sub_ln701_5_fu_377_p2 = (!sub_ln701_3_reg_730.read().is_01() || !grp_ProjY_fu_312_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_3_reg_730.read()) - sc_biguint<17>(grp_ProjY_fu_312_ap_return.read()));
}

void jet_hw::thread_sub_ln701_6_fu_382_p2() {
    sub_ln701_6_fu_382_p2 = (!sub_ln701_4_fu_372_p2.read().is_01() || !grp_ProjX_fu_286_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_4_fu_372_p2.read()) - sc_biguint<17>(grp_ProjX_fu_286_ap_return.read()));
}

void jet_hw::thread_sub_ln701_7_fu_388_p2() {
    sub_ln701_7_fu_388_p2 = (!sub_ln701_5_fu_377_p2.read().is_01() || !grp_ProjY_fu_322_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_5_fu_377_p2.read()) - sc_biguint<17>(grp_ProjY_fu_322_ap_return.read()));
}

void jet_hw::thread_sub_ln701_8_fu_394_p2() {
    sub_ln701_8_fu_394_p2 = (!sub_ln701_6_reg_735.read().is_01() || !grp_ProjX_fu_276_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_6_reg_735.read()) - sc_biguint<17>(grp_ProjX_fu_276_ap_return.read()));
}

void jet_hw::thread_sub_ln701_9_fu_399_p2() {
    sub_ln701_9_fu_399_p2 = (!sub_ln701_7_reg_740.read().is_01() || !grp_ProjY_fu_312_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(sub_ln701_7_reg_740.read()) - sc_biguint<17>(grp_ProjY_fu_312_ap_return.read()));
}

void jet_hw::thread_sub_ln701_fu_348_p2() {
    sub_ln701_fu_348_p2 = (!ap_const_lv17_0.is_01() || !grp_ProjX_fu_276_ap_return.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_biguint<17>(grp_ProjX_fu_276_ap_return.read()));
}

void jet_hw::thread_tmp_2_fu_541_p4() {
    tmp_2_fu_541_p4 = select_ln247_1_fu_533_p3.read().range(15, 12);
}

void jet_hw::thread_x_V_1_fu_497_p2() {
    x_V_1_fu_497_p2 = (!ap_const_lv16_0.is_01() || !x_V_reg_779.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(x_V_reg_779.read()));
}

void jet_hw::thread_x_V_3_fu_502_p3() {
    x_V_3_fu_502_p3 = (!tmp_reg_791.read()[0].is_01())? sc_lv<16>(): ((tmp_reg_791.read()[0].to_bool())? x_V_1_fu_497_p2.read(): x_V_reg_779.read());
}

void jet_hw::thread_x_V_fu_460_p1() {
    x_V_fu_460_p1 = sub_ln701_18_fu_448_p2.read().range(16-1, 0);
}

void jet_hw::thread_xor_ln237_fu_680_p2() {
    xor_ln237_fu_680_p2 = (icmp_ln237_reg_810.read() ^ ap_const_lv1_1);
}

void jet_hw::thread_y_V_1_fu_508_p2() {
    y_V_1_fu_508_p2 = (!ap_const_lv16_0.is_01() || !y_V_reg_785.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(y_V_reg_785.read()));
}

void jet_hw::thread_y_V_fu_464_p1() {
    y_V_fu_464_p1 = sub_ln701_19_fu_454_p2.read().range(16-1, 0);
}

void jet_hw::thread_zext_ln260_fu_617_p1() {
    zext_ln260_fu_617_p1 = esl_zext<10,9>(select_ln260_fu_610_p3.read());
}

void jet_hw::thread_zext_ln262_fu_639_p1() {
    zext_ln262_fu_639_p1 = esl_zext<11,10>(select_ln262_fu_631_p3.read());
}

void jet_hw::thread_zext_ln544_1_fu_597_p1() {
    zext_ln544_1_fu_597_p1 = esl_zext<64,7>(atan_index_V_reg_851.read());
}

void jet_hw::thread_zext_ln544_fu_557_p1() {
    zext_ln544_fu_557_p1 = esl_zext<64,16>(select_ln247_1_fu_533_p3.read());
}

void jet_hw::thread_zext_ln895_fu_601_p1() {
    zext_ln895_fu_601_p1 = esl_zext<9,7>(atan_table4_load_reg_861.read());
}

void jet_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_1to2.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reset_idle_pp0.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        case 32 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage5_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

void jet_hw::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_0_V\" :  \"" << jet_pt_0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_1_V\" :  \"" << jet_pt_1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_2_V\" :  \"" << jet_pt_2_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_3_V\" :  \"" << jet_pt_3_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_4_V\" :  \"" << jet_pt_4_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_5_V\" :  \"" << jet_pt_5_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_6_V\" :  \"" << jet_pt_6_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_7_V\" :  \"" << jet_pt_7_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_8_V\" :  \"" << jet_pt_8_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_pt_9_V\" :  \"" << jet_pt_9_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_0_V\" :  \"" << jet_phi_0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_1_V\" :  \"" << jet_phi_1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_2_V\" :  \"" << jet_phi_2_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_3_V\" :  \"" << jet_phi_3_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_4_V\" :  \"" << jet_phi_4_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_5_V\" :  \"" << jet_phi_5_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_6_V\" :  \"" << jet_phi_6_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_7_V\" :  \"" << jet_phi_7_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_8_V\" :  \"" << jet_phi_8_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"jet_phi_9_V\" :  \"" << jet_phi_9_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"met_pt2_V\" :  \"" << met_pt2_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"met_pt2_V_ap_vld\" :  \"" << met_pt2_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"met_phi_V\" :  \"" << met_phi_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"met_phi_V_ap_vld\" :  \"" << met_phi_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

