// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ProjY_HH_
#define _ProjY_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "jet_hw_mul_mul_16ns_16ns_32_1_1.h"
#include "ProjY_sin_table2.h"

namespace ap_rtl {

struct ProjY : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > ap_ce;
    sc_in< sc_lv<16> > pt_V;
    sc_in< sc_lv<11> > phi_V;
    sc_out< sc_lv<17> > ap_return;


    // Module declarations
    ProjY(sc_module_name name);
    SC_HAS_PROCESS(ProjY);

    ~ProjY();

    sc_trace_file* mVcdFile;

    ProjY_sin_table2* sin_table2_U;
    jet_hw_mul_mul_16ns_16ns_32_1_1<1,1,16,16,32>* jet_hw_mul_mul_16ns_16ns_32_1_1_U6;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<8> > sin_table2_address0;
    sc_signal< sc_logic > sin_table2_ce0;
    sc_signal< sc_lv<16> > sin_table2_q0;
    sc_signal< sc_lv<16> > pt_V_read_reg_172;
    sc_signal< sc_lv<16> > pt_V_read_reg_172_pp0_iter1_reg;
    sc_signal< sc_lv<1> > tmp_33_fu_93_p3;
    sc_signal< sc_lv<1> > tmp_33_reg_177;
    sc_signal< sc_lv<1> > tmp_33_reg_177_pp0_iter1_reg;
    sc_signal< sc_lv<1> > tmp_33_reg_177_pp0_iter2_reg;
    sc_signal< sc_lv<16> > sin_table2_load_reg_187;
    sc_signal< sc_lv<16> > tmp_reg_192;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_lv<64> > zext_ln544_fu_129_p1;
    sc_signal< sc_lv<3> > tmp_32_fu_63_p4;
    sc_signal< sc_lv<8> > phiQ1_V_fu_59_p1;
    sc_signal< sc_lv<1> > icmp_ln891_fu_73_p2;
    sc_signal< sc_lv<8> > phiQ1_V_1_fu_79_p2;
    sc_signal< sc_lv<8> > phiQ1_V_2_fu_85_p3;
    sc_signal< sc_lv<1> > icmp_ln891_1_fu_101_p2;
    sc_signal< sc_lv<8> > phiQ1_V_3_fu_107_p2;
    sc_signal< sc_lv<8> > select_ln118_fu_113_p3;
    sc_signal< sc_lv<8> > select_ln887_fu_121_p3;
    sc_signal< sc_lv<32> > ret_V_fu_165_p2;
    sc_signal< sc_lv<17> > zext_ln1503_fu_149_p1;
    sc_signal< sc_lv<17> > sub_ln68_fu_152_p2;
    sc_signal< sc_lv<16> > ret_V_fu_165_p0;
    sc_signal< sc_lv<16> > ret_V_fu_165_p1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0_0to2;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_reset_start_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<32> > ret_V_fu_165_p00;
    sc_signal< sc_lv<32> > ret_V_fu_165_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<11> ap_const_lv11_6FF;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<17> ap_const_lv17_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to2();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_reset_start_pp0();
    void thread_ap_return();
    void thread_icmp_ln891_1_fu_101_p2();
    void thread_icmp_ln891_fu_73_p2();
    void thread_phiQ1_V_1_fu_79_p2();
    void thread_phiQ1_V_2_fu_85_p3();
    void thread_phiQ1_V_3_fu_107_p2();
    void thread_phiQ1_V_fu_59_p1();
    void thread_ret_V_fu_165_p0();
    void thread_ret_V_fu_165_p00();
    void thread_ret_V_fu_165_p1();
    void thread_ret_V_fu_165_p10();
    void thread_select_ln118_fu_113_p3();
    void thread_select_ln887_fu_121_p3();
    void thread_sin_table2_address0();
    void thread_sin_table2_ce0();
    void thread_sub_ln68_fu_152_p2();
    void thread_tmp_32_fu_63_p4();
    void thread_tmp_33_fu_93_p3();
    void thread_zext_ln1503_fu_149_p1();
    void thread_zext_ln544_fu_129_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
