// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="jet_hw,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2104-2L-e,HLS_INPUT_CLOCK=4.167000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.610750,HLS_SYN_LAT=38,HLS_SYN_TPT=6,HLS_SYN_MEM=4,HLS_SYN_DSP=6,HLS_SYN_FF=2330,HLS_SYN_LUT=3499,HLS_VERSION=2019_1}" *)

module jet_hw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        jet_pt_0_V,
        jet_pt_1_V,
        jet_pt_2_V,
        jet_pt_3_V,
        jet_pt_4_V,
        jet_pt_5_V,
        jet_pt_6_V,
        jet_pt_7_V,
        jet_pt_8_V,
        jet_pt_9_V,
        jet_phi_0_V,
        jet_phi_1_V,
        jet_phi_2_V,
        jet_phi_3_V,
        jet_phi_4_V,
        jet_phi_5_V,
        jet_phi_6_V,
        jet_phi_7_V,
        jet_phi_8_V,
        jet_phi_9_V,
        met_pt2_V,
        met_pt2_V_ap_vld,
        met_phi_V,
        met_phi_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 6'd1;
parameter    ap_ST_fsm_pp0_stage1 = 6'd2;
parameter    ap_ST_fsm_pp0_stage2 = 6'd4;
parameter    ap_ST_fsm_pp0_stage3 = 6'd8;
parameter    ap_ST_fsm_pp0_stage4 = 6'd16;
parameter    ap_ST_fsm_pp0_stage5 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] jet_pt_0_V;
input  [15:0] jet_pt_1_V;
input  [15:0] jet_pt_2_V;
input  [15:0] jet_pt_3_V;
input  [15:0] jet_pt_4_V;
input  [15:0] jet_pt_5_V;
input  [15:0] jet_pt_6_V;
input  [15:0] jet_pt_7_V;
input  [15:0] jet_pt_8_V;
input  [15:0] jet_pt_9_V;
input  [10:0] jet_phi_0_V;
input  [10:0] jet_phi_1_V;
input  [10:0] jet_phi_2_V;
input  [10:0] jet_phi_3_V;
input  [10:0] jet_phi_4_V;
input  [10:0] jet_phi_5_V;
input  [10:0] jet_phi_6_V;
input  [10:0] jet_phi_7_V;
input  [10:0] jet_phi_8_V;
input  [10:0] jet_phi_9_V;
output  [31:0] met_pt2_V;
output   met_pt2_V_ap_vld;
output  [10:0] met_phi_V;
output   met_phi_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg met_pt2_V_ap_vld;
reg met_phi_V_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state12_pp0_stage5_iter1;
wire    ap_block_state18_pp0_stage5_iter2;
wire    ap_block_state24_pp0_stage5_iter3;
wire    ap_block_state30_pp0_stage5_iter4;
wire    ap_block_state36_pp0_stage5_iter5;
wire    ap_block_pp0_stage5_11001;
wire   [6:0] atan_table4_address0;
reg    atan_table4_ce0;
wire   [6:0] atan_table4_q0;
wire   [16:0] sub_ln701_2_fu_361_p2;
reg   [16:0] sub_ln701_2_reg_635;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state10_pp0_stage3_iter1;
wire    ap_block_state16_pp0_stage3_iter2;
wire    ap_block_state22_pp0_stage3_iter3;
wire    ap_block_state28_pp0_stage3_iter4;
wire    ap_block_state34_pp0_stage3_iter5;
wire    ap_block_pp0_stage3_11001;
wire   [16:0] sub_ln701_3_fu_367_p2;
reg   [16:0] sub_ln701_3_reg_640;
wire   [16:0] sub_ln701_6_fu_383_p2;
reg   [16:0] sub_ln701_6_reg_645;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state11_pp0_stage4_iter1;
wire    ap_block_state17_pp0_stage4_iter2;
wire    ap_block_state23_pp0_stage4_iter3;
wire    ap_block_state29_pp0_stage4_iter4;
wire    ap_block_state35_pp0_stage4_iter5;
wire    ap_block_pp0_stage4_11001;
wire   [16:0] sub_ln701_7_fu_389_p2;
reg   [16:0] sub_ln701_7_reg_650;
wire   [16:0] sub_ln701_10_fu_405_p2;
reg   [16:0] sub_ln701_10_reg_655;
wire   [16:0] sub_ln701_11_fu_411_p2;
reg   [16:0] sub_ln701_11_reg_660;
wire   [16:0] sub_ln701_14_fu_427_p2;
reg   [16:0] sub_ln701_14_reg_665;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state13_pp0_stage0_iter2;
wire    ap_block_state19_pp0_stage0_iter3;
wire    ap_block_state25_pp0_stage0_iter4;
wire    ap_block_state31_pp0_stage0_iter5;
wire    ap_block_state37_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_11001;
wire   [16:0] sub_ln701_15_fu_433_p2;
reg   [16:0] sub_ln701_15_reg_670;
wire  signed [16:0] sub_ln701_18_fu_449_p2;
reg  signed [16:0] sub_ln701_18_reg_675;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state8_pp0_stage1_iter1;
wire    ap_block_state14_pp0_stage1_iter2;
wire    ap_block_state20_pp0_stage1_iter3;
wire    ap_block_state26_pp0_stage1_iter4;
wire    ap_block_state32_pp0_stage1_iter5;
wire    ap_block_state38_pp0_stage1_iter6;
wire    ap_block_pp0_stage1_11001;
reg  signed [16:0] sub_ln701_18_reg_675_pp0_iter2_reg;
wire  signed [16:0] sub_ln701_19_fu_455_p2;
reg  signed [16:0] sub_ln701_19_reg_682;
wire  signed [31:0] mul_ln214_1_fu_622_p2;
reg  signed [31:0] mul_ln214_1_reg_689;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state9_pp0_stage2_iter1;
wire    ap_block_state15_pp0_stage2_iter2;
wire    ap_block_state21_pp0_stage2_iter3;
wire    ap_block_state27_pp0_stage2_iter4;
wire    ap_block_state33_pp0_stage2_iter5;
wire    ap_block_state39_pp0_stage2_iter6;
wire    ap_block_pp0_stage2_11001;
wire   [0:0] icmp_ln185_fu_468_p2;
reg   [0:0] icmp_ln185_reg_694;
reg   [0:0] icmp_ln185_reg_694_pp0_iter2_reg;
reg   [0:0] icmp_ln185_reg_694_pp0_iter3_reg;
reg   [0:0] icmp_ln185_reg_694_pp0_iter4_reg;
reg   [0:0] icmp_ln185_reg_694_pp0_iter5_reg;
reg   [0:0] tmp_31_reg_698;
reg   [0:0] tmp_31_reg_698_pp0_iter2_reg;
reg   [0:0] tmp_31_reg_698_pp0_iter3_reg;
reg   [0:0] tmp_31_reg_698_pp0_iter4_reg;
reg   [0:0] tmp_31_reg_698_pp0_iter5_reg;
wire  signed [31:0] grp_fu_628_p3;
reg   [31:0] tmp_V_reg_703;
reg  signed [31:0] tmp_V_reg_703_pp0_iter2_reg;
reg  signed [31:0] tmp_V_reg_703_pp0_iter3_reg;
reg  signed [31:0] tmp_V_reg_703_pp0_iter4_reg;
wire   [16:0] grp_sqrt_fixed_33_33_s_fu_272_ap_return;
reg   [16:0] p_Val2_3_reg_709;
wire  signed [16:0] grp_fu_484_p2;
reg  signed [16:0] ret_V_reg_714;
wire   [18:0] sub_ln1371_fu_512_p2;
reg   [18:0] sub_ln1371_reg_719;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage2_subdone;
reg    grp_sqrt_fixed_33_33_s_fu_272_ap_ce;
wire    ap_block_state5_pp0_stage4_iter0_ignore_call0;
wire    ap_block_state11_pp0_stage4_iter1_ignore_call0;
wire    ap_block_state17_pp0_stage4_iter2_ignore_call0;
wire    ap_block_state23_pp0_stage4_iter3_ignore_call0;
wire    ap_block_state29_pp0_stage4_iter4_ignore_call0;
wire    ap_block_state35_pp0_stage4_iter5_ignore_call0;
wire    ap_block_pp0_stage4_11001_ignoreCallOp169;
wire    ap_block_state6_pp0_stage5_iter0_ignore_call0;
wire    ap_block_state12_pp0_stage5_iter1_ignore_call0;
wire    ap_block_state18_pp0_stage5_iter2_ignore_call0;
wire    ap_block_state24_pp0_stage5_iter3_ignore_call0;
wire    ap_block_state30_pp0_stage5_iter4_ignore_call0;
wire    ap_block_state36_pp0_stage5_iter5_ignore_call0;
wire    ap_block_pp0_stage5_11001_ignoreCallOp170;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state7_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state13_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state19_pp0_stage0_iter3_ignore_call0;
wire    ap_block_state25_pp0_stage0_iter4_ignore_call0;
wire    ap_block_state31_pp0_stage0_iter5_ignore_call0;
wire    ap_block_state37_pp0_stage0_iter6_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp171;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call0;
wire    ap_block_state8_pp0_stage1_iter1_ignore_call0;
wire    ap_block_state14_pp0_stage1_iter2_ignore_call0;
wire    ap_block_state20_pp0_stage1_iter3_ignore_call0;
wire    ap_block_state26_pp0_stage1_iter4_ignore_call0;
wire    ap_block_state32_pp0_stage1_iter5_ignore_call0;
wire    ap_block_state38_pp0_stage1_iter6_ignore_call0;
wire    ap_block_pp0_stage1_11001_ignoreCallOp172;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call0;
wire    ap_block_state9_pp0_stage2_iter1_ignore_call0;
wire    ap_block_state15_pp0_stage2_iter2_ignore_call0;
wire    ap_block_state21_pp0_stage2_iter3_ignore_call0;
wire    ap_block_state27_pp0_stage2_iter4_ignore_call0;
wire    ap_block_state33_pp0_stage2_iter5_ignore_call0;
wire    ap_block_state39_pp0_stage2_iter6_ignore_call0;
wire    ap_block_pp0_stage2_11001_ignoreCallOp173;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call0;
wire    ap_block_state10_pp0_stage3_iter1_ignore_call0;
wire    ap_block_state16_pp0_stage3_iter2_ignore_call0;
wire    ap_block_state22_pp0_stage3_iter3_ignore_call0;
wire    ap_block_state28_pp0_stage3_iter4_ignore_call0;
wire    ap_block_state34_pp0_stage3_iter5_ignore_call0;
wire    ap_block_pp0_stage3_11001_ignoreCallOp174;
reg    grp_ProjX_fu_277_ap_start;
wire    grp_ProjX_fu_277_ap_done;
wire    grp_ProjX_fu_277_ap_idle;
wire    grp_ProjX_fu_277_ap_ready;
reg   [15:0] grp_ProjX_fu_277_pt_V;
reg   [10:0] grp_ProjX_fu_277_phi_V;
wire   [16:0] grp_ProjX_fu_277_ap_return;
reg    grp_ProjX_fu_287_ap_start;
wire    grp_ProjX_fu_287_ap_done;
wire    grp_ProjX_fu_287_ap_idle;
wire    grp_ProjX_fu_287_ap_ready;
reg   [15:0] grp_ProjX_fu_287_pt_V;
reg   [10:0] grp_ProjX_fu_287_phi_V;
wire   [16:0] grp_ProjX_fu_287_ap_return;
reg    grp_ProjY_fu_313_ap_start;
wire    grp_ProjY_fu_313_ap_done;
wire    grp_ProjY_fu_313_ap_idle;
wire    grp_ProjY_fu_313_ap_ready;
reg   [15:0] grp_ProjY_fu_313_pt_V;
reg   [10:0] grp_ProjY_fu_313_phi_V;
wire   [16:0] grp_ProjY_fu_313_ap_return;
reg    grp_ProjY_fu_323_ap_start;
wire    grp_ProjY_fu_323_ap_done;
wire    grp_ProjY_fu_323_ap_idle;
wire    grp_ProjY_fu_323_ap_ready;
reg   [15:0] grp_ProjY_fu_323_pt_V;
reg   [10:0] grp_ProjY_fu_323_phi_V;
wire   [16:0] grp_ProjY_fu_323_ap_return;
reg   [7:0] ap_phi_mux_ssdm_int_V_write_ass_phi_fu_265_p4;
wire   [7:0] select_ln191_fu_609_p3;
reg   [7:0] ap_phi_reg_pp0_iter6_ssdm_int_V_write_ass_reg_261;
wire    ap_block_pp0_stage2;
wire   [7:0] ap_phi_reg_pp0_iter0_ssdm_int_V_write_ass_reg_261;
reg   [7:0] ap_phi_reg_pp0_iter1_ssdm_int_V_write_ass_reg_261;
reg   [7:0] ap_phi_reg_pp0_iter2_ssdm_int_V_write_ass_reg_261;
reg   [7:0] ap_phi_reg_pp0_iter3_ssdm_int_V_write_ass_reg_261;
reg   [7:0] ap_phi_reg_pp0_iter4_ssdm_int_V_write_ass_reg_261;
reg   [7:0] ap_phi_reg_pp0_iter5_ssdm_int_V_write_ass_reg_261;
wire    ap_block_pp0_stage4;
reg    grp_ProjX_fu_277_ap_start_reg;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage5;
reg    grp_ProjX_fu_287_ap_start_reg;
reg    grp_ProjY_fu_313_ap_start_reg;
reg    grp_ProjY_fu_323_ap_start_reg;
wire   [63:0] select_ln190_fu_590_p3;
wire    ap_block_pp0_stage3_01001;
wire    ap_block_pp0_stage2_01001;
wire   [16:0] sub_ln701_fu_349_p2;
wire   [16:0] sub_ln701_1_fu_355_p2;
wire   [16:0] sub_ln701_4_fu_373_p2;
wire   [16:0] sub_ln701_5_fu_378_p2;
wire   [16:0] sub_ln701_8_fu_395_p2;
wire   [16:0] sub_ln701_9_fu_400_p2;
wire   [16:0] sub_ln701_12_fu_417_p2;
wire   [16:0] sub_ln701_13_fu_422_p2;
wire   [16:0] sub_ln701_16_fu_439_p2;
wire   [16:0] sub_ln701_17_fu_444_p2;
wire   [16:0] or_ln185_fu_464_p2;
wire   [15:0] trunc_ln1371_1_fu_488_p4;
wire   [15:0] xor_ln1371_fu_498_p2;
wire  signed [17:0] sext_ln1371_1_fu_504_p1;
wire   [18:0] zext_ln1371_fu_508_p1;
wire  signed [17:0] sext_ln1371_fu_518_p1;
wire   [17:0] add_ln1371_fu_521_p2;
wire   [16:0] trunc_ln1371_2_fu_535_p4;
wire  signed [17:0] sext_ln1371_2_fu_545_p1;
wire   [0:0] tmp_fu_527_p3;
wire   [18:0] zext_ln1371_1_fu_549_p1;
wire   [18:0] select_ln1371_fu_553_p3;
wire   [17:0] trunc_ln187_fu_560_p1;
wire   [0:0] tmp_30_fu_570_p3;
wire   [0:0] icmp_ln189_fu_564_p2;
wire   [0:0] xor_ln189_fu_578_p2;
wire   [0:0] and_ln189_fu_584_p2;
wire   [7:0] zext_ln887_fu_599_p1;
wire   [7:0] sub_ln68_fu_603_p2;
wire  signed [16:0] mul_ln214_1_fu_622_p0;
wire  signed [31:0] sext_ln214_1_fu_461_p1;
wire  signed [16:0] mul_ln214_1_fu_622_p1;
wire  signed [16:0] grp_fu_628_p0;
wire  signed [31:0] sext_ln214_fu_481_p1;
wire  signed [16:0] grp_fu_628_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to6;
wire    ap_block_pp0_stage1_subdone;
reg    ap_idle_pp0_0to5;
reg    ap_reset_idle_pp0;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_ProjX_fu_277_ap_start_reg = 1'b0;
#0 grp_ProjX_fu_287_ap_start_reg = 1'b0;
#0 grp_ProjY_fu_313_ap_start_reg = 1'b0;
#0 grp_ProjY_fu_323_ap_start_reg = 1'b0;
end

jet_hw_atan_table4 #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
atan_table4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(atan_table4_address0),
    .ce0(atan_table4_ce0),
    .q0(atan_table4_q0)
);

sqrt_fixed_33_33_s grp_sqrt_fixed_33_33_s_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x_V(tmp_V_reg_703),
    .ap_return(grp_sqrt_fixed_33_33_s_fu_272_ap_return),
    .ap_ce(grp_sqrt_fixed_33_33_s_fu_272_ap_ce)
);

ProjX grp_ProjX_fu_277(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjX_fu_277_ap_start),
    .ap_done(grp_ProjX_fu_277_ap_done),
    .ap_idle(grp_ProjX_fu_277_ap_idle),
    .ap_ready(grp_ProjX_fu_277_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjX_fu_277_pt_V),
    .phi_V(grp_ProjX_fu_277_phi_V),
    .ap_return(grp_ProjX_fu_277_ap_return)
);

ProjX grp_ProjX_fu_287(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjX_fu_287_ap_start),
    .ap_done(grp_ProjX_fu_287_ap_done),
    .ap_idle(grp_ProjX_fu_287_ap_idle),
    .ap_ready(grp_ProjX_fu_287_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjX_fu_287_pt_V),
    .phi_V(grp_ProjX_fu_287_phi_V),
    .ap_return(grp_ProjX_fu_287_ap_return)
);

ProjY grp_ProjY_fu_313(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjY_fu_313_ap_start),
    .ap_done(grp_ProjY_fu_313_ap_done),
    .ap_idle(grp_ProjY_fu_313_ap_idle),
    .ap_ready(grp_ProjY_fu_313_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjY_fu_313_pt_V),
    .phi_V(grp_ProjY_fu_313_phi_V),
    .ap_return(grp_ProjY_fu_313_ap_return)
);

ProjY grp_ProjY_fu_323(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjY_fu_323_ap_start),
    .ap_done(grp_ProjY_fu_323_ap_done),
    .ap_idle(grp_ProjY_fu_323_ap_idle),
    .ap_ready(grp_ProjY_fu_323_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjY_fu_323_pt_V),
    .phi_V(grp_ProjY_fu_323_phi_V),
    .ap_return(grp_ProjY_fu_323_ap_return)
);

jet_hw_udiv_17s_17ns_17_21_1 #(
    .ID( 1 ),
    .NUM_STAGE( 21 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
jet_hw_udiv_17s_17ns_17_21_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln701_18_reg_675_pp0_iter2_reg),
    .din1(p_Val2_3_reg_709),
    .ce(1'b1),
    .dout(grp_fu_484_p2)
);

jet_hw_mul_mul_17s_17s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 32 ))
jet_hw_mul_mul_17s_17s_32_1_1_U12(
    .din0(mul_ln214_1_fu_622_p0),
    .din1(mul_ln214_1_fu_622_p1),
    .dout(mul_ln214_1_fu_622_p2)
);

jet_hw_mac_muladd_17s_17s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
jet_hw_mac_muladd_17s_17s_32s_32_1_1_U13(
    .din0(grp_fu_628_p0),
    .din1(grp_fu_628_p1),
    .din2(mul_ln214_1_reg_689),
    .dout(grp_fu_628_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjX_fu_277_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjX_fu_277_ap_start_reg <= 1'b1;
        end else if ((grp_ProjX_fu_277_ap_ready == 1'b1)) begin
            grp_ProjX_fu_277_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjX_fu_287_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjX_fu_287_ap_start_reg <= 1'b1;
        end else if ((grp_ProjX_fu_287_ap_ready == 1'b1)) begin
            grp_ProjX_fu_287_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjY_fu_313_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjY_fu_313_ap_start_reg <= 1'b1;
        end else if ((grp_ProjY_fu_313_ap_ready == 1'b1)) begin
            grp_ProjY_fu_313_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjY_fu_323_ap_start_reg <= 1'b0;
    end else begin
        if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjY_fu_323_ap_start_reg <= 1'b1;
        end else if ((grp_ProjY_fu_323_ap_ready == 1'b1)) begin
            grp_ProjY_fu_323_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_fu_468_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_phi_reg_pp0_iter1_ssdm_int_V_write_ass_reg_261 <= 8'd0;
    end else if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_phi_reg_pp0_iter1_ssdm_int_V_write_ass_reg_261 <= ap_phi_reg_pp0_iter0_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_reg_pp0_iter2_ssdm_int_V_write_ass_reg_261 <= ap_phi_reg_pp0_iter1_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_ssdm_int_V_write_ass_reg_261 <= ap_phi_reg_pp0_iter2_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_ssdm_int_V_write_ass_reg_261 <= ap_phi_reg_pp0_iter3_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_ssdm_int_V_write_ass_reg_261 <= ap_phi_reg_pp0_iter4_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_ssdm_int_V_write_ass_reg_261 <= ap_phi_reg_pp0_iter5_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        icmp_ln185_reg_694 <= icmp_ln185_fu_468_p2;
        icmp_ln185_reg_694_pp0_iter2_reg <= icmp_ln185_reg_694;
        icmp_ln185_reg_694_pp0_iter3_reg <= icmp_ln185_reg_694_pp0_iter2_reg;
        icmp_ln185_reg_694_pp0_iter4_reg <= icmp_ln185_reg_694_pp0_iter3_reg;
        icmp_ln185_reg_694_pp0_iter5_reg <= icmp_ln185_reg_694_pp0_iter4_reg;
        mul_ln214_1_reg_689 <= mul_ln214_1_fu_622_p2;
        tmp_31_reg_698_pp0_iter2_reg <= tmp_31_reg_698;
        tmp_31_reg_698_pp0_iter3_reg <= tmp_31_reg_698_pp0_iter2_reg;
        tmp_31_reg_698_pp0_iter4_reg <= tmp_31_reg_698_pp0_iter3_reg;
        tmp_31_reg_698_pp0_iter5_reg <= tmp_31_reg_698_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_reg_694_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        p_Val2_3_reg_709 <= grp_sqrt_fixed_33_33_s_fu_272_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_reg_694_pp0_iter5_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ret_V_reg_714 <= grp_fu_484_p2;
        sub_ln1371_reg_719 <= sub_ln1371_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        sub_ln701_10_reg_655 <= sub_ln701_10_fu_405_p2;
        sub_ln701_11_reg_660 <= sub_ln701_11_fu_411_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sub_ln701_14_reg_665 <= sub_ln701_14_fu_427_p2;
        sub_ln701_15_reg_670 <= sub_ln701_15_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sub_ln701_18_reg_675 <= sub_ln701_18_fu_449_p2;
        sub_ln701_18_reg_675_pp0_iter2_reg <= sub_ln701_18_reg_675;
        sub_ln701_19_reg_682 <= sub_ln701_19_fu_455_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        sub_ln701_2_reg_635 <= sub_ln701_2_fu_361_p2;
        sub_ln701_3_reg_640 <= sub_ln701_3_fu_367_p2;
        tmp_V_reg_703_pp0_iter2_reg <= tmp_V_reg_703;
        tmp_V_reg_703_pp0_iter3_reg <= tmp_V_reg_703_pp0_iter2_reg;
        tmp_V_reg_703_pp0_iter4_reg <= tmp_V_reg_703_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        sub_ln701_6_reg_645 <= sub_ln701_6_fu_383_p2;
        sub_ln701_7_reg_650 <= sub_ln701_7_fu_389_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln185_fu_468_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        tmp_31_reg_698 <= sub_ln701_19_reg_682[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        tmp_V_reg_703 <= grp_fu_628_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to6 = 1'b1;
    end else begin
        ap_idle_pp0_1to6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (icmp_ln185_reg_694_pp0_iter5_reg == 1'd0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_phi_mux_ssdm_int_V_write_ass_phi_fu_265_p4 = select_ln191_fu_609_p3;
    end else begin
        ap_phi_mux_ssdm_int_V_write_ass_phi_fu_265_p4 = ap_phi_reg_pp0_iter6_ssdm_int_V_write_ass_reg_261;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to5 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        atan_table4_ce0 = 1'b1;
    end else begin
        atan_table4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjX_fu_277_ap_start = 1'b1;
    end else begin
        grp_ProjX_fu_277_ap_start = grp_ProjX_fu_277_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_277_phi_V = jet_phi_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_277_phi_V = jet_phi_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_277_phi_V = jet_phi_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_277_phi_V = jet_phi_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_277_phi_V = jet_phi_0_V;
        end else begin
            grp_ProjX_fu_277_phi_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_277_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_277_pt_V = jet_pt_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_277_pt_V = jet_pt_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_277_pt_V = jet_pt_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_277_pt_V = jet_pt_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_277_pt_V = jet_pt_0_V;
        end else begin
            grp_ProjX_fu_277_pt_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_277_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjX_fu_287_ap_start = 1'b1;
    end else begin
        grp_ProjX_fu_287_ap_start = grp_ProjX_fu_287_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_287_phi_V = jet_phi_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_287_phi_V = jet_phi_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_287_phi_V = jet_phi_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_287_phi_V = jet_phi_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_287_phi_V = jet_phi_1_V;
        end else begin
            grp_ProjX_fu_287_phi_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_287_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_287_pt_V = jet_pt_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_287_pt_V = jet_pt_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_287_pt_V = jet_pt_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_287_pt_V = jet_pt_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_287_pt_V = jet_pt_1_V;
        end else begin
            grp_ProjX_fu_287_pt_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_287_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjY_fu_313_ap_start = 1'b1;
    end else begin
        grp_ProjY_fu_313_ap_start = grp_ProjY_fu_313_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_313_phi_V = jet_phi_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_313_phi_V = jet_phi_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_313_phi_V = jet_phi_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_313_phi_V = jet_phi_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_313_phi_V = jet_phi_0_V;
        end else begin
            grp_ProjY_fu_313_phi_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_313_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_313_pt_V = jet_pt_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_313_pt_V = jet_pt_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_313_pt_V = jet_pt_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_313_pt_V = jet_pt_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_313_pt_V = jet_pt_0_V;
        end else begin
            grp_ProjY_fu_313_pt_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_313_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjY_fu_323_ap_start = 1'b1;
    end else begin
        grp_ProjY_fu_323_ap_start = grp_ProjY_fu_323_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_323_phi_V = jet_phi_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_323_phi_V = jet_phi_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_323_phi_V = jet_phi_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_323_phi_V = jet_phi_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_323_phi_V = jet_phi_1_V;
        end else begin
            grp_ProjY_fu_323_phi_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_323_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_323_pt_V = jet_pt_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_323_pt_V = jet_pt_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_323_pt_V = jet_pt_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_323_pt_V = jet_pt_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_323_pt_V = jet_pt_1_V;
        end else begin
            grp_ProjY_fu_323_pt_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_323_pt_V = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001_ignoreCallOp170) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp171) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp173) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp172) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp169) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp174) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_sqrt_fixed_33_33_s_fu_272_ap_ce = 1'b1;
    end else begin
        grp_sqrt_fixed_33_33_s_fu_272_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        met_phi_V_ap_vld = 1'b1;
    end else begin
        met_phi_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        met_pt2_V_ap_vld = 1'b1;
    end else begin
        met_pt2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to6 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1371_fu_521_p2 = ($signed(18'd1) + $signed(sext_ln1371_fu_518_p1));

assign and_ln189_fu_584_p2 = (xor_ln189_fu_578_p2 & icmp_ln189_fu_564_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp171 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp172 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp173 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_ignoreCallOp174 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_ignoreCallOp169 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001_ignoreCallOp170 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage4_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage5_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage4_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage5_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call0 = (ap_start == 1'b0);
end

assign ap_block_state20_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage2_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage3_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage4_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage5_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage5_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage4_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage5_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage5_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage2_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage3_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage4_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage4_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage5_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage5_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage1_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage2_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_ssdm_int_V_write_ass_reg_261 = 'bx;

assign atan_table4_address0 = select_ln190_fu_590_p3;

assign grp_fu_628_p0 = sext_ln214_fu_481_p1;

assign grp_fu_628_p1 = sext_ln214_fu_481_p1;

assign icmp_ln185_fu_468_p2 = ((or_ln185_fu_464_p2 == 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_564_p2 = ((trunc_ln187_fu_560_p1 != 18'd0) ? 1'b1 : 1'b0);

assign met_phi_V = $signed(ap_phi_mux_ssdm_int_V_write_ass_phi_fu_265_p4);

assign met_pt2_V = tmp_V_reg_703_pp0_iter4_reg;

assign mul_ln214_1_fu_622_p0 = sext_ln214_1_fu_461_p1;

assign mul_ln214_1_fu_622_p1 = sext_ln214_1_fu_461_p1;

assign or_ln185_fu_464_p2 = (sub_ln701_19_reg_682 | sub_ln701_18_reg_675);

assign select_ln1371_fu_553_p3 = ((tmp_fu_527_p3[0:0] === 1'b1) ? sub_ln1371_reg_719 : zext_ln1371_1_fu_549_p1);

assign select_ln190_fu_590_p3 = ((and_ln189_fu_584_p2[0:0] === 1'b1) ? 64'd127 : 64'd0);

assign select_ln191_fu_609_p3 = ((tmp_31_reg_698_pp0_iter5_reg[0:0] === 1'b1) ? sub_ln68_fu_603_p2 : zext_ln887_fu_599_p1);

assign sext_ln1371_1_fu_504_p1 = $signed(xor_ln1371_fu_498_p2);

assign sext_ln1371_2_fu_545_p1 = $signed(trunc_ln1371_2_fu_535_p4);

assign sext_ln1371_fu_518_p1 = ret_V_reg_714;

assign sext_ln214_1_fu_461_p1 = sub_ln701_19_reg_682;

assign sext_ln214_fu_481_p1 = sub_ln701_18_reg_675;

assign sub_ln1371_fu_512_p2 = (19'd0 - zext_ln1371_fu_508_p1);

assign sub_ln68_fu_603_p2 = (8'd0 - zext_ln887_fu_599_p1);

assign sub_ln701_10_fu_405_p2 = (sub_ln701_8_fu_395_p2 - grp_ProjX_fu_287_ap_return);

assign sub_ln701_11_fu_411_p2 = (sub_ln701_9_fu_400_p2 - grp_ProjY_fu_323_ap_return);

assign sub_ln701_12_fu_417_p2 = (sub_ln701_10_reg_655 - grp_ProjX_fu_277_ap_return);

assign sub_ln701_13_fu_422_p2 = (sub_ln701_11_reg_660 - grp_ProjY_fu_313_ap_return);

assign sub_ln701_14_fu_427_p2 = (sub_ln701_12_fu_417_p2 - grp_ProjX_fu_287_ap_return);

assign sub_ln701_15_fu_433_p2 = (sub_ln701_13_fu_422_p2 - grp_ProjY_fu_323_ap_return);

assign sub_ln701_16_fu_439_p2 = (sub_ln701_14_reg_665 - grp_ProjX_fu_277_ap_return);

assign sub_ln701_17_fu_444_p2 = (sub_ln701_15_reg_670 - grp_ProjY_fu_313_ap_return);

assign sub_ln701_18_fu_449_p2 = (sub_ln701_16_fu_439_p2 - grp_ProjX_fu_287_ap_return);

assign sub_ln701_19_fu_455_p2 = (sub_ln701_17_fu_444_p2 - grp_ProjY_fu_323_ap_return);

assign sub_ln701_1_fu_355_p2 = (17'd0 - grp_ProjY_fu_313_ap_return);

assign sub_ln701_2_fu_361_p2 = (sub_ln701_fu_349_p2 - grp_ProjX_fu_287_ap_return);

assign sub_ln701_3_fu_367_p2 = (sub_ln701_1_fu_355_p2 - grp_ProjY_fu_323_ap_return);

assign sub_ln701_4_fu_373_p2 = (sub_ln701_2_reg_635 - grp_ProjX_fu_277_ap_return);

assign sub_ln701_5_fu_378_p2 = (sub_ln701_3_reg_640 - grp_ProjY_fu_313_ap_return);

assign sub_ln701_6_fu_383_p2 = (sub_ln701_4_fu_373_p2 - grp_ProjX_fu_287_ap_return);

assign sub_ln701_7_fu_389_p2 = (sub_ln701_5_fu_378_p2 - grp_ProjY_fu_323_ap_return);

assign sub_ln701_8_fu_395_p2 = (sub_ln701_6_reg_645 - grp_ProjX_fu_277_ap_return);

assign sub_ln701_9_fu_400_p2 = (sub_ln701_7_reg_650 - grp_ProjY_fu_313_ap_return);

assign sub_ln701_fu_349_p2 = (17'd0 - grp_ProjX_fu_277_ap_return);

assign tmp_30_fu_570_p3 = select_ln1371_fu_553_p3[32'd18];

assign tmp_fu_527_p3 = add_ln1371_fu_521_p2[32'd17];

assign trunc_ln1371_1_fu_488_p4 = {{grp_fu_484_p2[16:1]}};

assign trunc_ln1371_2_fu_535_p4 = {{add_ln1371_fu_521_p2[17:1]}};

assign trunc_ln187_fu_560_p1 = select_ln1371_fu_553_p3[17:0];

assign xor_ln1371_fu_498_p2 = (trunc_ln1371_1_fu_488_p4 ^ 16'd65535);

assign xor_ln189_fu_578_p2 = (tmp_30_fu_570_p3 ^ 1'd1);

assign zext_ln1371_1_fu_549_p1 = $unsigned(sext_ln1371_2_fu_545_p1);

assign zext_ln1371_fu_508_p1 = $unsigned(sext_ln1371_1_fu_504_p1);

assign zext_ln887_fu_599_p1 = atan_table4_q0;

endmodule //jet_hw
