// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="jet_hw,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2104-2L-e,HLS_INPUT_CLOCK=4.167000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.643500,HLS_SYN_LAT=13,HLS_SYN_TPT=6,HLS_SYN_MEM=8,HLS_SYN_DSP=7,HLS_SYN_FF=969,HLS_SYN_LUT=1690,HLS_VERSION=2019_1}" *)

module jet_hw (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        jet_pt_0_V,
        jet_pt_1_V,
        jet_pt_2_V,
        jet_pt_3_V,
        jet_pt_4_V,
        jet_pt_5_V,
        jet_pt_6_V,
        jet_pt_7_V,
        jet_pt_8_V,
        jet_pt_9_V,
        jet_phi_0_V,
        jet_phi_1_V,
        jet_phi_2_V,
        jet_phi_3_V,
        jet_phi_4_V,
        jet_phi_5_V,
        jet_phi_6_V,
        jet_phi_7_V,
        jet_phi_8_V,
        jet_phi_9_V,
        met_pt2_V,
        met_pt2_V_ap_vld,
        met_phi_V,
        met_phi_V_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 6'd1;
parameter    ap_ST_fsm_pp0_stage1 = 6'd2;
parameter    ap_ST_fsm_pp0_stage2 = 6'd4;
parameter    ap_ST_fsm_pp0_stage3 = 6'd8;
parameter    ap_ST_fsm_pp0_stage4 = 6'd16;
parameter    ap_ST_fsm_pp0_stage5 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] jet_pt_0_V;
input  [15:0] jet_pt_1_V;
input  [15:0] jet_pt_2_V;
input  [15:0] jet_pt_3_V;
input  [15:0] jet_pt_4_V;
input  [15:0] jet_pt_5_V;
input  [15:0] jet_pt_6_V;
input  [15:0] jet_pt_7_V;
input  [15:0] jet_pt_8_V;
input  [15:0] jet_pt_9_V;
input  [10:0] jet_phi_0_V;
input  [10:0] jet_phi_1_V;
input  [10:0] jet_phi_2_V;
input  [10:0] jet_phi_3_V;
input  [10:0] jet_phi_4_V;
input  [10:0] jet_phi_5_V;
input  [10:0] jet_phi_6_V;
input  [10:0] jet_phi_7_V;
input  [10:0] jet_phi_8_V;
input  [10:0] jet_phi_9_V;
output  [31:0] met_pt2_V;
output   met_pt2_V_ap_vld;
output  [10:0] met_phi_V;
output   met_phi_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg met_pt2_V_ap_vld;
reg met_phi_V_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state12_pp0_stage5_iter1;
wire    ap_block_pp0_stage5_11001;
wire   [11:0] inv_table3_address0;
reg    inv_table3_ce0;
wire   [15:0] inv_table3_q0;
wire   [6:0] atan_table4_address0;
reg    atan_table4_ce0;
wire   [6:0] atan_table4_q0;
wire   [16:0] sub_ln701_2_fu_360_p2;
reg   [16:0] sub_ln701_2_reg_725;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state10_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
wire   [16:0] sub_ln701_3_fu_366_p2;
reg   [16:0] sub_ln701_3_reg_730;
wire   [16:0] sub_ln701_6_fu_382_p2;
reg   [16:0] sub_ln701_6_reg_735;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state11_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_11001;
wire   [16:0] sub_ln701_7_fu_388_p2;
reg   [16:0] sub_ln701_7_reg_740;
wire   [16:0] sub_ln701_10_fu_404_p2;
reg   [16:0] sub_ln701_10_reg_745;
wire   [16:0] sub_ln701_11_fu_410_p2;
reg   [16:0] sub_ln701_11_reg_750;
wire   [16:0] sub_ln701_14_fu_426_p2;
reg   [16:0] sub_ln701_14_reg_755;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state7_pp0_stage0_iter1;
wire    ap_block_state13_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [16:0] sub_ln701_15_fu_432_p2;
reg   [16:0] sub_ln701_15_reg_760;
wire  signed [16:0] sub_ln701_18_fu_448_p2;
reg  signed [16:0] sub_ln701_18_reg_765;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state8_pp0_stage1_iter1;
wire    ap_block_state14_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire  signed [16:0] sub_ln701_19_fu_454_p2;
reg  signed [16:0] sub_ln701_19_reg_772;
wire   [15:0] x_V_fu_460_p1;
reg   [15:0] x_V_reg_779;
wire   [15:0] y_V_fu_464_p1;
reg   [15:0] y_V_reg_785;
reg   [0:0] tmp_reg_791;
reg   [0:0] tmp_1_reg_798;
wire  signed [31:0] mul_ln214_1_fu_706_p2;
reg  signed [31:0] mul_ln214_1_reg_805;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state9_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire   [0:0] icmp_ln237_fu_491_p2;
reg   [0:0] icmp_ln237_reg_810;
wire  signed [15:0] select_ln247_fu_525_p3;
reg  signed [15:0] select_ln247_reg_816;
wire   [0:0] icmp_ln891_fu_551_p2;
reg   [0:0] icmp_ln891_reg_821;
wire   [0:0] icmp_ln895_1_fu_562_p2;
reg   [0:0] icmp_ln895_1_reg_831;
wire   [0:0] icmp_ln895_2_fu_568_p2;
reg   [0:0] icmp_ln895_2_reg_836;
wire  signed [15:0] select_ln891_fu_576_p3;
reg  signed [15:0] select_ln891_reg_841;
wire   [0:0] icmp_ln895_3_fu_583_p2;
reg   [0:0] icmp_ln895_3_reg_846;
reg   [6:0] atan_index_V_reg_851;
reg   [6:0] atan_table4_load_reg_861;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage1_subdone;
reg    grp_ProjX_fu_276_ap_start;
wire    grp_ProjX_fu_276_ap_done;
wire    grp_ProjX_fu_276_ap_idle;
wire    grp_ProjX_fu_276_ap_ready;
reg   [15:0] grp_ProjX_fu_276_pt_V;
reg   [10:0] grp_ProjX_fu_276_phi_V;
wire   [16:0] grp_ProjX_fu_276_ap_return;
reg    grp_ProjX_fu_286_ap_start;
wire    grp_ProjX_fu_286_ap_done;
wire    grp_ProjX_fu_286_ap_idle;
wire    grp_ProjX_fu_286_ap_ready;
reg   [15:0] grp_ProjX_fu_286_pt_V;
reg   [10:0] grp_ProjX_fu_286_phi_V;
wire   [16:0] grp_ProjX_fu_286_ap_return;
reg    grp_ProjY_fu_312_ap_start;
wire    grp_ProjY_fu_312_ap_done;
wire    grp_ProjY_fu_312_ap_idle;
wire    grp_ProjY_fu_312_ap_ready;
reg   [15:0] grp_ProjY_fu_312_pt_V;
reg   [10:0] grp_ProjY_fu_312_phi_V;
wire   [16:0] grp_ProjY_fu_312_ap_return;
reg    grp_ProjY_fu_322_ap_start;
wire    grp_ProjY_fu_322_ap_done;
wire    grp_ProjY_fu_322_ap_idle;
wire    grp_ProjY_fu_322_ap_ready;
reg   [15:0] grp_ProjY_fu_322_pt_V;
reg   [10:0] grp_ProjY_fu_322_phi_V;
wire   [16:0] grp_ProjY_fu_322_ap_return;
reg    grp_ProjX_fu_276_ap_start_reg;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage5;
reg    grp_ProjX_fu_286_ap_start_reg;
reg    grp_ProjY_fu_312_ap_start_reg;
reg    grp_ProjY_fu_322_ap_start_reg;
wire   [63:0] zext_ln544_fu_557_p1;
wire   [63:0] zext_ln544_1_fu_597_p1;
wire  signed [31:0] grp_fu_712_p3;
wire    ap_block_pp0_stage3_01001;
wire    ap_block_pp0_stage1_01001;
wire   [16:0] sub_ln701_fu_348_p2;
wire   [16:0] sub_ln701_1_fu_354_p2;
wire   [16:0] sub_ln701_4_fu_372_p2;
wire   [16:0] sub_ln701_5_fu_377_p2;
wire   [16:0] sub_ln701_8_fu_394_p2;
wire   [16:0] sub_ln701_9_fu_399_p2;
wire   [16:0] sub_ln701_12_fu_416_p2;
wire   [16:0] sub_ln701_13_fu_421_p2;
wire   [16:0] sub_ln701_16_fu_438_p2;
wire   [16:0] sub_ln701_17_fu_443_p2;
wire   [16:0] or_ln237_fu_487_p2;
wire   [15:0] x_V_1_fu_497_p2;
wire   [15:0] y_V_1_fu_508_p2;
wire   [15:0] x_V_3_fu_502_p3;
wire   [15:0] a_V_fu_513_p3;
wire   [0:0] icmp_ln895_fu_519_p2;
wire   [15:0] select_ln247_1_fu_533_p3;
wire   [3:0] tmp_2_fu_541_p4;
wire  signed [15:0] a_over_b_V_fu_720_p2;
wire   [8:0] zext_ln895_fu_601_p1;
wire   [8:0] sub_ln68_fu_604_p2;
wire   [8:0] select_ln260_fu_610_p3;
wire   [9:0] zext_ln260_fu_617_p1;
wire   [0:0] and_ln262_fu_621_p2;
wire   [9:0] sub_ln68_1_fu_625_p2;
wire   [9:0] select_ln262_fu_631_p3;
wire   [9:0] sub_ln68_2_fu_643_p2;
wire  signed [10:0] sext_ln68_fu_649_p1;
wire   [10:0] zext_ln262_fu_639_p1;
wire   [10:0] select_ln263_fu_653_p3;
wire   [10:0] select_ln895_fu_660_p3;
wire   [10:0] add_ln68_fu_667_p2;
wire   [0:0] xor_ln237_fu_680_p2;
wire   [0:0] and_ln887_fu_685_p2;
wire   [10:0] select_ln264_fu_673_p3;
wire   [10:0] select_ln887_fu_690_p3;
wire  signed [16:0] mul_ln214_1_fu_706_p0;
wire  signed [31:0] sext_ln214_1_fu_484_p1;
wire  signed [16:0] mul_ln214_1_fu_706_p1;
wire  signed [16:0] grp_fu_712_p0;
wire  signed [31:0] sext_ln214_fu_573_p1;
wire  signed [16:0] grp_fu_712_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_ProjX_fu_276_ap_start_reg = 1'b0;
#0 grp_ProjX_fu_286_ap_start_reg = 1'b0;
#0 grp_ProjY_fu_312_ap_start_reg = 1'b0;
#0 grp_ProjY_fu_322_ap_start_reg = 1'b0;
end

jet_hw_inv_table3 #(
    .DataWidth( 16 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
inv_table3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inv_table3_address0),
    .ce0(inv_table3_ce0),
    .q0(inv_table3_q0)
);

jet_hw_atan_table4 #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
atan_table4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(atan_table4_address0),
    .ce0(atan_table4_ce0),
    .q0(atan_table4_q0)
);

ProjX grp_ProjX_fu_276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjX_fu_276_ap_start),
    .ap_done(grp_ProjX_fu_276_ap_done),
    .ap_idle(grp_ProjX_fu_276_ap_idle),
    .ap_ready(grp_ProjX_fu_276_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjX_fu_276_pt_V),
    .phi_V(grp_ProjX_fu_276_phi_V),
    .ap_return(grp_ProjX_fu_276_ap_return)
);

ProjX grp_ProjX_fu_286(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjX_fu_286_ap_start),
    .ap_done(grp_ProjX_fu_286_ap_done),
    .ap_idle(grp_ProjX_fu_286_ap_idle),
    .ap_ready(grp_ProjX_fu_286_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjX_fu_286_pt_V),
    .phi_V(grp_ProjX_fu_286_phi_V),
    .ap_return(grp_ProjX_fu_286_ap_return)
);

ProjY grp_ProjY_fu_312(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjY_fu_312_ap_start),
    .ap_done(grp_ProjY_fu_312_ap_done),
    .ap_idle(grp_ProjY_fu_312_ap_idle),
    .ap_ready(grp_ProjY_fu_312_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjY_fu_312_pt_V),
    .phi_V(grp_ProjY_fu_312_phi_V),
    .ap_return(grp_ProjY_fu_312_ap_return)
);

ProjY grp_ProjY_fu_322(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ProjY_fu_322_ap_start),
    .ap_done(grp_ProjY_fu_322_ap_done),
    .ap_idle(grp_ProjY_fu_322_ap_idle),
    .ap_ready(grp_ProjY_fu_322_ap_ready),
    .ap_ce(1'b1),
    .pt_V(grp_ProjY_fu_322_pt_V),
    .phi_V(grp_ProjY_fu_322_phi_V),
    .ap_return(grp_ProjY_fu_322_ap_return)
);

jet_hw_mul_mul_17s_17s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 32 ))
jet_hw_mul_mul_17s_17s_32_1_1_U10(
    .din0(mul_ln214_1_fu_706_p0),
    .din1(mul_ln214_1_fu_706_p1),
    .dout(mul_ln214_1_fu_706_p2)
);

jet_hw_mac_muladd_17s_17s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
jet_hw_mac_muladd_17s_17s_32s_32_1_1_U11(
    .din0(grp_fu_712_p0),
    .din1(grp_fu_712_p1),
    .din2(mul_ln214_1_reg_805),
    .dout(grp_fu_712_p3)
);

jet_hw_mul_mul_16s_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
jet_hw_mul_mul_16s_16s_16_1_1_U12(
    .din0(select_ln247_reg_816),
    .din1(select_ln891_reg_841),
    .dout(a_over_b_V_fu_720_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage5_subdone) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjX_fu_276_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjX_fu_276_ap_start_reg <= 1'b1;
        end else if ((grp_ProjX_fu_276_ap_ready == 1'b1)) begin
            grp_ProjX_fu_276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjX_fu_286_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjX_fu_286_ap_start_reg <= 1'b1;
        end else if ((grp_ProjX_fu_286_ap_ready == 1'b1)) begin
            grp_ProjX_fu_286_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjY_fu_312_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjY_fu_312_ap_start_reg <= 1'b1;
        end else if ((grp_ProjY_fu_312_ap_ready == 1'b1)) begin
            grp_ProjY_fu_312_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ProjY_fu_322_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
            grp_ProjY_fu_322_ap_start_reg <= 1'b1;
        end else if ((grp_ProjY_fu_322_ap_ready == 1'b1)) begin
            grp_ProjY_fu_322_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (icmp_ln237_reg_810 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        atan_index_V_reg_851 <= {{a_over_b_V_fu_720_p2[15:9]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln237_reg_810 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        atan_table4_load_reg_861 <= atan_table4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        icmp_ln237_reg_810 <= icmp_ln237_fu_491_p2;
        icmp_ln891_reg_821 <= icmp_ln891_fu_551_p2;
        icmp_ln895_1_reg_831 <= icmp_ln895_1_fu_562_p2;
        icmp_ln895_2_reg_836 <= icmp_ln895_2_fu_568_p2;
        mul_ln214_1_reg_805 <= mul_ln214_1_fu_706_p2;
        select_ln247_reg_816 <= select_ln247_fu_525_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln237_reg_810 == 1'd0))) begin
        icmp_ln895_3_reg_846 <= icmp_ln895_3_fu_583_p2;
        select_ln891_reg_841 <= select_ln891_fu_576_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        sub_ln701_10_reg_745 <= sub_ln701_10_fu_404_p2;
        sub_ln701_11_reg_750 <= sub_ln701_11_fu_410_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sub_ln701_14_reg_755 <= sub_ln701_14_fu_426_p2;
        sub_ln701_15_reg_760 <= sub_ln701_15_fu_432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sub_ln701_18_reg_765 <= sub_ln701_18_fu_448_p2;
        sub_ln701_19_reg_772 <= sub_ln701_19_fu_454_p2;
        tmp_1_reg_798 <= sub_ln701_19_fu_454_p2[32'd16];
        tmp_reg_791 <= sub_ln701_18_fu_448_p2[32'd16];
        x_V_reg_779 <= x_V_fu_460_p1;
        y_V_reg_785 <= y_V_fu_464_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sub_ln701_2_reg_725 <= sub_ln701_2_fu_360_p2;
        sub_ln701_3_reg_730 <= sub_ln701_3_fu_366_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        sub_ln701_6_reg_735 <= sub_ln701_6_fu_382_p2;
        sub_ln701_7_reg_740 <= sub_ln701_7_fu_388_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        atan_table4_ce0 = 1'b1;
    end else begin
        atan_table4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjX_fu_276_ap_start = 1'b1;
    end else begin
        grp_ProjX_fu_276_ap_start = grp_ProjX_fu_276_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_276_phi_V = jet_phi_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_276_phi_V = jet_phi_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_276_phi_V = jet_phi_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_276_phi_V = jet_phi_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_276_phi_V = jet_phi_0_V;
        end else begin
            grp_ProjX_fu_276_phi_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_276_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_276_pt_V = jet_pt_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_276_pt_V = jet_pt_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_276_pt_V = jet_pt_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_276_pt_V = jet_pt_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_276_pt_V = jet_pt_0_V;
        end else begin
            grp_ProjX_fu_276_pt_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_276_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjX_fu_286_ap_start = 1'b1;
    end else begin
        grp_ProjX_fu_286_ap_start = grp_ProjX_fu_286_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_286_phi_V = jet_phi_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_286_phi_V = jet_phi_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_286_phi_V = jet_phi_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_286_phi_V = jet_phi_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_286_phi_V = jet_phi_1_V;
        end else begin
            grp_ProjX_fu_286_phi_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_286_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjX_fu_286_pt_V = jet_pt_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjX_fu_286_pt_V = jet_pt_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjX_fu_286_pt_V = jet_pt_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjX_fu_286_pt_V = jet_pt_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjX_fu_286_pt_V = jet_pt_1_V;
        end else begin
            grp_ProjX_fu_286_pt_V = 'bx;
        end
    end else begin
        grp_ProjX_fu_286_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjY_fu_312_ap_start = 1'b1;
    end else begin
        grp_ProjY_fu_312_ap_start = grp_ProjY_fu_312_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_312_phi_V = jet_phi_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_312_phi_V = jet_phi_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_312_phi_V = jet_phi_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_312_phi_V = jet_phi_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_312_phi_V = jet_phi_0_V;
        end else begin
            grp_ProjY_fu_312_phi_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_312_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_312_pt_V = jet_pt_8_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_312_pt_V = jet_pt_6_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_312_pt_V = jet_pt_4_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_312_pt_V = jet_pt_2_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_312_pt_V = jet_pt_0_V;
        end else begin
            grp_ProjY_fu_312_pt_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_312_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        grp_ProjY_fu_322_ap_start = 1'b1;
    end else begin
        grp_ProjY_fu_322_ap_start = grp_ProjY_fu_322_ap_start_reg;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_322_phi_V = jet_phi_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_322_phi_V = jet_phi_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_322_phi_V = jet_phi_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_322_phi_V = jet_phi_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_322_phi_V = jet_phi_1_V;
        end else begin
            grp_ProjY_fu_322_phi_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_322_phi_V = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_ProjY_fu_322_pt_V = jet_pt_9_V;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_ProjY_fu_322_pt_V = jet_pt_7_V;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_ProjY_fu_322_pt_V = jet_pt_5_V;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_ProjY_fu_322_pt_V = jet_pt_3_V;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_ProjY_fu_322_pt_V = jet_pt_1_V;
        end else begin
            grp_ProjY_fu_322_pt_V = 'bx;
        end
    end else begin
        grp_ProjY_fu_322_pt_V = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        inv_table3_ce0 = 1'b1;
    end else begin
        inv_table3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        met_phi_V_ap_vld = 1'b1;
    end else begin
        met_phi_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        met_pt2_V_ap_vld = 1'b1;
    end else begin
        met_pt2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_V_fu_513_p3 = ((tmp_1_reg_798[0:0] === 1'b1) ? y_V_1_fu_508_p2 : y_V_reg_785);

assign add_ln68_fu_667_p2 = ($signed(11'd1536) + $signed(select_ln895_fu_660_p3));

assign and_ln262_fu_621_p2 = (tmp_reg_791 & icmp_ln895_2_reg_836);

assign and_ln887_fu_685_p2 = (xor_ln237_fu_680_p2 & tmp_reg_791);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign atan_table4_address0 = zext_ln544_1_fu_597_p1;

assign grp_fu_712_p0 = sext_ln214_fu_573_p1;

assign grp_fu_712_p1 = sext_ln214_fu_573_p1;

assign icmp_ln237_fu_491_p2 = ((or_ln237_fu_487_p2 == 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_551_p2 = ((tmp_2_fu_541_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_1_fu_562_p2 = ((a_V_fu_513_p3 > x_V_3_fu_502_p3) ? 1'b1 : 1'b0);

assign icmp_ln895_2_fu_568_p2 = (($signed(sub_ln701_19_reg_772) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln895_3_fu_583_p2 = (($signed(sub_ln701_18_reg_765) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_519_p2 = ((x_V_3_fu_502_p3 > a_V_fu_513_p3) ? 1'b1 : 1'b0);

assign inv_table3_address0 = zext_ln544_fu_557_p1;

assign met_phi_V = ((icmp_ln237_reg_810[0:0] === 1'b1) ? 11'd0 : select_ln887_fu_690_p3);

assign met_pt2_V = grp_fu_712_p3;

assign mul_ln214_1_fu_706_p0 = sext_ln214_1_fu_484_p1;

assign mul_ln214_1_fu_706_p1 = sext_ln214_1_fu_484_p1;

assign or_ln237_fu_487_p2 = (sub_ln701_19_reg_772 | sub_ln701_18_reg_765);

assign select_ln247_1_fu_533_p3 = ((icmp_ln895_fu_519_p2[0:0] === 1'b1) ? x_V_3_fu_502_p3 : a_V_fu_513_p3);

assign select_ln247_fu_525_p3 = ((icmp_ln895_fu_519_p2[0:0] === 1'b1) ? a_V_fu_513_p3 : x_V_3_fu_502_p3);

assign select_ln260_fu_610_p3 = ((icmp_ln895_1_reg_831[0:0] === 1'b1) ? sub_ln68_fu_604_p2 : zext_ln895_fu_601_p1);

assign select_ln262_fu_631_p3 = ((and_ln262_fu_621_p2[0:0] === 1'b1) ? sub_ln68_1_fu_625_p2 : zext_ln260_fu_617_p1);

assign select_ln263_fu_653_p3 = ((tmp_1_reg_798[0:0] === 1'b1) ? sext_ln68_fu_649_p1 : zext_ln262_fu_639_p1);

assign select_ln264_fu_673_p3 = ((tmp_1_reg_798[0:0] === 1'b1) ? add_ln68_fu_667_p2 : select_ln895_fu_660_p3);

assign select_ln887_fu_690_p3 = ((and_ln887_fu_685_p2[0:0] === 1'b1) ? select_ln264_fu_673_p3 : select_ln895_fu_660_p3);

assign select_ln891_fu_576_p3 = ((icmp_ln891_reg_821[0:0] === 1'b1) ? 16'd1 : inv_table3_q0);

assign select_ln895_fu_660_p3 = ((icmp_ln895_3_reg_846[0:0] === 1'b1) ? select_ln263_fu_653_p3 : zext_ln262_fu_639_p1);

assign sext_ln214_1_fu_484_p1 = sub_ln701_19_reg_772;

assign sext_ln214_fu_573_p1 = sub_ln701_18_reg_765;

assign sext_ln68_fu_649_p1 = $signed(sub_ln68_2_fu_643_p2);

assign sub_ln68_1_fu_625_p2 = ($signed(10'd512) - $signed(zext_ln260_fu_617_p1));

assign sub_ln68_2_fu_643_p2 = (10'd0 - select_ln262_fu_631_p3);

assign sub_ln68_fu_604_p2 = ($signed(9'd256) - $signed(zext_ln895_fu_601_p1));

assign sub_ln701_10_fu_404_p2 = (sub_ln701_8_fu_394_p2 - grp_ProjX_fu_286_ap_return);

assign sub_ln701_11_fu_410_p2 = (sub_ln701_9_fu_399_p2 - grp_ProjY_fu_322_ap_return);

assign sub_ln701_12_fu_416_p2 = (sub_ln701_10_reg_745 - grp_ProjX_fu_276_ap_return);

assign sub_ln701_13_fu_421_p2 = (sub_ln701_11_reg_750 - grp_ProjY_fu_312_ap_return);

assign sub_ln701_14_fu_426_p2 = (sub_ln701_12_fu_416_p2 - grp_ProjX_fu_286_ap_return);

assign sub_ln701_15_fu_432_p2 = (sub_ln701_13_fu_421_p2 - grp_ProjY_fu_322_ap_return);

assign sub_ln701_16_fu_438_p2 = (sub_ln701_14_reg_755 - grp_ProjX_fu_276_ap_return);

assign sub_ln701_17_fu_443_p2 = (sub_ln701_15_reg_760 - grp_ProjY_fu_312_ap_return);

assign sub_ln701_18_fu_448_p2 = (sub_ln701_16_fu_438_p2 - grp_ProjX_fu_286_ap_return);

assign sub_ln701_19_fu_454_p2 = (sub_ln701_17_fu_443_p2 - grp_ProjY_fu_322_ap_return);

assign sub_ln701_1_fu_354_p2 = (17'd0 - grp_ProjY_fu_312_ap_return);

assign sub_ln701_2_fu_360_p2 = (sub_ln701_fu_348_p2 - grp_ProjX_fu_286_ap_return);

assign sub_ln701_3_fu_366_p2 = (sub_ln701_1_fu_354_p2 - grp_ProjY_fu_322_ap_return);

assign sub_ln701_4_fu_372_p2 = (sub_ln701_2_reg_725 - grp_ProjX_fu_276_ap_return);

assign sub_ln701_5_fu_377_p2 = (sub_ln701_3_reg_730 - grp_ProjY_fu_312_ap_return);

assign sub_ln701_6_fu_382_p2 = (sub_ln701_4_fu_372_p2 - grp_ProjX_fu_286_ap_return);

assign sub_ln701_7_fu_388_p2 = (sub_ln701_5_fu_377_p2 - grp_ProjY_fu_322_ap_return);

assign sub_ln701_8_fu_394_p2 = (sub_ln701_6_reg_735 - grp_ProjX_fu_276_ap_return);

assign sub_ln701_9_fu_399_p2 = (sub_ln701_7_reg_740 - grp_ProjY_fu_312_ap_return);

assign sub_ln701_fu_348_p2 = (17'd0 - grp_ProjX_fu_276_ap_return);

assign tmp_2_fu_541_p4 = {{select_ln247_1_fu_533_p3[15:12]}};

assign x_V_1_fu_497_p2 = (16'd0 - x_V_reg_779);

assign x_V_3_fu_502_p3 = ((tmp_reg_791[0:0] === 1'b1) ? x_V_1_fu_497_p2 : x_V_reg_779);

assign x_V_fu_460_p1 = sub_ln701_18_fu_448_p2[15:0];

assign xor_ln237_fu_680_p2 = (icmp_ln237_reg_810 ^ 1'd1);

assign y_V_1_fu_508_p2 = (16'd0 - y_V_reg_785);

assign y_V_fu_464_p1 = sub_ln701_19_fu_454_p2[15:0];

assign zext_ln260_fu_617_p1 = select_ln260_fu_610_p3;

assign zext_ln262_fu_639_p1 = select_ln262_fu_631_p3;

assign zext_ln544_1_fu_597_p1 = atan_index_V_reg_851;

assign zext_ln544_fu_557_p1 = select_ln247_1_fu_533_p3;

assign zext_ln895_fu_601_p1 = atan_table4_load_reg_861;

endmodule //jet_hw
